// chess_app.js embedded (53678 bytes, 1329 lines)
static const char chess_app_js_content[] =
    "// ============================================================================\n"
    "// CHESS WEB APP - EXTRACTED JAVASCRIPT FOR SYNTAX CHECKING\n"
    "// ============================================================================\n"
    "\n"
    "console.log('🚀 Chess JavaScript loading...');\n"
    "\n"
    "// ============================================================================\n"
    "// PIECE SYMBOLS AND GLOBAL VARIABLES\n"
    "// ============================================================================\n"
    "\n"
    "const pieceSymbols = {\n"
    "    'R': '♜', 'N': '♞', 'B': '♝', 'Q': '♛', 'K': '♚', 'P': '♟',\n"
    "    'r': '♖', 'n': '♘', 'b': '♗', 'q': '♕', 'k': '♔', 'p': '♙',\n"
    "    ' ': ' '\n"
    "};\n"
    "\n"
    "let boardData = [];\n"
    "let statusData = {};\n"
    "let historyData = [];\n"
    "let capturedData = { white_captured: [], black_captured: [] };\n"
    "let advantageData = { history: [], white_checks: 0, black_checks: 0, white_castles: 0, black_castles: 0 };\n"
    "let selectedSquare = null;\n"
    "let reviewMode = false;\n"
    "let currentReviewIndex = -1;\n"
    "let initialBoard = [];\n"
    "let sandboxMode = false;\n"
    "let sandboxBoard = [];\n"
    "let sandboxHistory = [];\n"
    "let endgameReportShown = false;\n"
    "\n"
    "// ============================================================================\n"
    "// BOARD FUNCTIONS\n"
    "// ============================================================================\n"
    "\n"
    "function createBoard() {\n"
    "    const board = document.getElementById('board');\n"
    "    board.innerHTML = '';\n"
    "    for (let row = 7; row >= 0; row--) {\n"
    "        for (let col = 0; col < 8; col++) {\n"
    "            const square = document.createElement('div');\n"
    "            square.className = 'square ' + ((row + col) % 2 === 0 ? 'light' : 'dark');\n"
    "            square.dataset.row = row;\n"
    "            square.dataset.col = col;\n"
    "            square.dataset.index = row * 8 + col;\n"
    "            square.onclick = () => handleSquareClick(row, col);\n"
    "            const piece = document.createElement('div');\n"
    "            piece.className = 'piece';\n"
    "            piece.id = 'piece-' + (row * 8 + col);\n"
    "            square.appendChild(piece);\n"
    "            board.appendChild(square);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "function clearHighlights() {\n"
    "    document.querySelectorAll('.square').forEach(sq => {\n"
    "        sq.classList.remove('selected', 'valid-move', 'valid-capture');\n"
    "    });\n"
    "    selectedSquare = null;\n"
    "}\n"
    "\n"
    "async function handleSquareClick(row, col) {\n"
    "    const piece = sandboxMode ? sandboxBoard[row][col] : boardData[row][col];\n"
    "    const index = row * 8 + col;\n"
    "\n"
    "    if (piece === ' ' && selectedSquare !== null) {\n"
    "        const fromRow = Math.floor(selectedSquare / 8);\n"
    "        const fromCol = selectedSquare % 8;\n"
    "\n"
    "        if (sandboxMode) {\n"
    "            makeSandboxMove(fromRow, fromCol, row, col);\n"
    "            clearHighlights();\n"
    "        } else {\n"
    "            const fromNotation = String.fromCharCode(97 + fromCol) + (8 - fromRow);\n"
    "            const toNotation = String.fromCharCode(97 + col) + (8 - row);\n"
    "            try {\n"
    "                const response = await fetch('/api/move', {\n"
    "                    method: 'POST',\n"
    "                    headers: { 'Content-Type': 'application/json' },\n"
    "                    body: JSON.stringify({ from: fromNotation, to: toNotation })\n"
    "                });\n"
    "                if (response.ok) {\n"
    "                    clearHighlights();\n"
    "                    fetchData();\n"
    "                }\n"
    "            } catch (error) {\n"
    "                console.error('Move error:', error);\n"
    "            }\n"
    "        }\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    if (piece !== ' ') {\n"
    "        if (sandboxMode) {\n"
    "            clearHighlights();\n"
    "            selectedSquare = index;\n"
    "            const square = document.querySelector(`[data-row='${row}'][data-col='${col}']`);\n"
    "            if (square) square.classList.add('selected');\n"
    "        } else {\n"
    "            const isWhitePiece = piece === piece.toUpperCase();\n"
    "            const currentPlayerIsWhite = statusData.current_player === 'White';\n"
    "\n"
    "            if ((isWhitePiece && currentPlayerIsWhite) || (!isWhitePiece && !currentPlayerIsWhite)) {\n"
    "                clearHighlights();\n"
    "                selectedSquare = index;\n"
    "                const square = document.querySelector(`[data-row='${row}'][data-col='${col}']`);\n"
    "                if (square) square.classList.add('selected');\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// REVIEW MODE\n"
    "// ============================================================================\n"
    "\n"
    "function reconstructBoardAtMove(moveIndex) {\n"
    "    const startBoard = [\n"
    "        ['R', 'N', 'B', 'Q', 'K', 'B', 'N', 'R'],\n"
    "        ['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P'],\n"
    "        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],\n"
    "        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],\n"
    "        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],\n"
    "        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],\n"
    "        ['p', 'p', 'p', 'p', 'p', 'p', 'p', 'p'],\n"
    "        ['r', 'n', 'b', 'q', 'k', 'b', 'n', 'r']\n"
    "    ];\n"
    "    const board = JSON.parse(JSON.stringify(startBoard));\n"
    "    for (let i = 0; i <= moveIndex && i < historyData.length; i++) {\n"
    "        const move = historyData[i];\n"
    "        const fromRow = parseInt(move.from[1]) - 1;\n"
    "        const fromCol = move.from.charCodeAt(0) - 97;\n"
    "        const toRow = parseInt(move.to[1]) - 1;\n"
    "        const toCol = move.to.charCodeAt(0) - 97;\n"
    "        board[toRow][toCol] = board[fromRow][fromCol];\n"
    "        board[fromRow][fromCol] = ' ';\n"
    "    }\n"
    "    return board;\n"
    "}\n"
    "\n"
    "function enterReviewMode(index) {\n"
    "    reviewMode = true;\n"
    "    currentReviewIndex = index;\n"
    "    const banner = document.getElementById('review-banner');\n"
    "    banner.classList.add('active');\n"
    "    document.getElementById('review-move-text').textContent = `Reviewing move ${index + 1}`;\n"
    "    const reconstructedBoard = reconstructBoardAtMove(index);\n"
    "    updateBoard(reconstructedBoard);\n"
    "    document.querySelectorAll('.square').forEach(sq => {\n"
    "        sq.classList.remove('move-from', 'move-to');\n"
    "    });\n"
    "    if (index >= 0 && index < historyData.length) {\n"
    "        const move = historyData[index];\n"
    "        const fromRow = parseInt(move.from[1]) - 1;\n"
    "        const fromCol = move.from.charCodeAt(0) - 97;\n"
    "        const toRow = parseInt(move.to[1]) - 1;\n"
    "        const toCol = move.to.charCodeAt(0) - 97;\n"
    "        const fromSquare = document.querySelector(`[data-row='${fromRow}'][data-col='${fromCol}']`);\n"
    "        const toSquare = document.querySelector(`[data-row='${toRow}'][data-col='${toCol}']`);\n"
    "        if (fromSquare) fromSquare.classList.add('move-from');\n"
    "        if (toSquare) toSquare.classList.add('move-to');\n"
    "    }\n"
    "    document.querySelectorAll('.history-item').forEach(item => {\n"
    "        item.classList.remove('selected');\n"
    "    });\n"
    "    const selectedItem = document.querySelector(`[data-move-index='${index}']`);\n"
    "    if (selectedItem) {\n"
    "        selectedItem.classList.add('selected');\n"
    "        selectedItem.scrollIntoView({ behavior: 'smooth', block: 'nearest' });\n"
    "    }\n"
    "}\n"
    "\n"
    "function exitReviewMode() {\n"
    "    reviewMode = false;\n"
    "    currentReviewIndex = -1;\n"
    "    document.getElementById('review-banner').classList.remove('active');\n"
    "    document.querySelectorAll('.square').forEach(sq => {\n"
    "        sq.classList.remove('move-from', 'move-to');\n"
    "    });\n"
    "    document.querySelectorAll('.history-item').forEach(item => {\n"
    "        item.classList.remove('selected');\n"
    "    });\n"
    "    fetchData();\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// SANDBOX MODE\n"
    "// ============================================================================\n"
    "\n"
    "function enterSandboxMode() {\n"
    "    sandboxMode = true;\n"
    "    sandboxBoard = JSON.parse(JSON.stringify(boardData));\n"
    "    sandboxHistory = [];\n"
    "    const banner = document.getElementById('sandbox-banner');\n"
    "    banner.classList.add('active');\n"
    "    clearHighlights();\n"
    "}\n"
    "\n"
    "function exitSandboxMode() {\n"
    "    sandboxMode = false;\n"
    "    sandboxBoard = [];\n"
    "    sandboxHistory = [];\n"
    "    document.getElementById('sandbox-banner').classList.remove('active');\n"
    "    clearHighlights();\n"
    "    fetchData();\n"
    "}\n"
    "\n"
    "function makeSandboxMove(fromRow, fromCol, toRow, toCol) {\n"
    "    const piece = sandboxBoard[fromRow][fromCol];\n"
    "    sandboxBoard[toRow][toCol] = piece;\n"
    "    sandboxBoard[fromRow][fromCol] = ' ';\n"
    "    sandboxHistory.push({ from: `${String.fromCharCode(97 + fromCol)}${8 - fromRow}`, to: `${String.fromCharCode(97 + toCol)}${8 - toRow}` });\n"
    "    updateBoard(sandboxBoard);\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// UPDATE FUNCTIONS\n"
    "// ============================================================================\n"
    "\n"
    "function updateBoard(board) {\n"
    "    boardData = board;\n"
    "    const loading = document.getElementById('loading');\n"
    "    if (loading) loading.style.display = 'none';\n"
    "    for (let row = 0; row < 8; row++) {\n"
    "        for (let col = 0; col < 8; col++) {\n"
    "            const piece = board[row][col];\n"
    "            const pieceElement = document.getElementById('piece-' + (row * 8 + col));\n"
    "            if (pieceElement) {\n"
    "                pieceElement.textContent = pieceSymbols[piece] || ' ';\n"
    "                if (piece !== ' ') {\n"
    "                    pieceElement.className = 'piece ' + (piece === piece.toUpperCase() ? 'white' : 'black');\n"
    "                } else {\n"
    "                    pieceElement.className = 'piece';\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// ENDGAME REPORT FUNCTIONS\n"
    "// ============================================================================\n"
    "\n"
    "// 🏆 Zobrazit endgame report na webu\n"
    "async function showEndgameReport(gameEnd) {\n"
    "    console.log('🏆 showEndgameReport() called with:', gameEnd);\n"
    "\n"
    "    // ✅ FIX: Pokud už je banner zobrazen, nedělat nic (aby se nepřekresloval)\n"
    "    if (endgameReportShown && document.getElementById('endgame-banner')) {\n"
    "        console.log('Endgame report already shown, skipping...');\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    // ✅ Načíst advantage history pro graf\n"
    "    let advantageDataLocal = { history: [], white_checks: 0, black_checks: 0, white_castles: 0, black_castles: 0 };\n"
    "    try {\n"
    "        const response = await fetch('/api/advantage');\n"
    "        advantageDataLocal = await response.json();\n"
    "        console.log('Advantage data loaded:', advantageDataLocal);\n"
    "    } catch (e) {\n"
    "        console.error('Failed to load advantage data:', e);\n"
    "    }\n"
    "\n"
    "    // Určit výsledek a barvy\n"
    "    let emoji = '🏆';\n"
    "    let title = '';\n"
    "    let subtitle = '';\n"
    "    let accentColor = '#4CAF50';\n"
    "    let bgGradient = 'linear-gradient(135deg, #1e3a1e, #2d4a2d)';\n"
    "\n"
    "    if (gameEnd.winner === 'Draw') {\n"
    "        emoji = '🤝';\n"
    "        title = 'REMÍZA';\n"
    "        subtitle = gameEnd.reason;\n"
    "        accentColor = '#FF9800';\n"
    "        bgGradient = 'linear-gradient(135deg, #3a2e1e, #4a3e2d)';\n"
    "    } else {\n"
    "        emoji = gameEnd.winner === 'White' ? '⚪' : '⚫';\n"
    "        title = `${gameEnd.winner.toUpperCase()} VYHRÁL!`;\n"
    "        subtitle = gameEnd.reason;\n"
    "        accentColor = gameEnd.winner === 'White' ? '#4CAF50' : '#2196F3';\n"
    "        bgGradient = gameEnd.winner === 'White' ? 'linear-gradient(135deg, #1e3a1e, #2d4a2d)' : 'linear-gradient(135deg, #1e2a3a, #2d3a4a)';\n"
    "    }\n"
    "\n"
    "    // Získat statistiky\n"
    "    const whiteMoves = Math.ceil(statusData.move_count / 2);\n"
    "    const blackMoves = Math.floor(statusData.move_count / 2);\n"
    "    const whiteCaptured = capturedData.white_captured || [];\n"
    "    const blackCaptured = capturedData.black_captured || [];\n"
    "\n"
    "    // Material advantage\n"
    "    const pieceValues = { p: 1, n: 3, b: 3, r: 5, q: 9, P: 1, N: 3, B: 3, R: 5, Q: 9 };\n"
    "    let whiteMaterial = 0, blackMaterial = 0;\n"
    "    whiteCaptured.forEach(p => whiteMaterial += pieceValues[p] || 0);\n"
    "    blackCaptured.forEach(p => blackMaterial += pieceValues[p] || 0);\n"
    "    const materialDiff = whiteMaterial - blackMaterial;\n"
    "    const materialText = materialDiff > 0 ? `White +${materialDiff}` : materialDiff < 0 ? `Black +${-materialDiff}` : 'Vyrovnáno';\n"
    "\n"
    "    // ✅ Vytvořit SVG graf výhody (jako chess.com)\n"
    "    let graphSVG = '';\n"
    "    if (advantageDataLocal.history && advantageDataLocal.history.length > 1) {\n"
    "        const history = advantageDataLocal.history;\n"
    "        const width = 280;\n"
    "        const height = 100;\n"
    "        const maxAdvantage = Math.max(10, ...history.map(Math.abs));\n"
    "        const scaleY = height / (2 * maxAdvantage);\n"
    "        const scaleX = width / (history.length - 1);\n"
    "\n"
    "        // Vytvořit body pro polyline (0,0 je nahoře vlevo, y roste dolů)\n"
    "        let points = history.map((adv, i) => {\n"
    "            const x = i * scaleX;\n"
    "            const y = height / 2 - adv * scaleY;  // Převrátit Y (White nahoře, Black dole)\n"
    "            return `${x},${y}`;\n"
    "        }).join(' ');\n"
    "\n"
    "        // Vytvořit polygon pro vyplněnou oblast\n"
    "        let areaPoints = `0,${height / 2} ${points} ${width},${height / 2}`;\n"
    "\n"
    "        graphSVG = `<svg width=\"280\" height=\"100\" style=\"border-radius:6px;background:rgba(0,0,0,0.2);\">\n"
    "            <!-- Středová čára (vyrovnaná pozice) -->\n"
    "            <line x1=\"0\" y1=\"${height / 2}\" x2=\"${width}\" y2=\"${height / 2}\" stroke=\"#555\" stroke-width=\"1\" stroke-dasharray=\"3,3\"/>\n"
    "            <!-- Vyplněná oblast pod křivkou -->\n"
    "            <polygon points=\"${areaPoints}\" fill=\"${accentColor}\" opacity=\"0.2\"/>\n"
    "            <!-- Křivka výhody -->\n"
    "            <polyline points=\"${points}\" fill=\"none\" stroke=\"${accentColor}\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\n"
    "            <!-- Tečky na koncích -->\n"
    "            <circle cx=\"0\" cy=\"${height / 2}\" r=\"3\" fill=\"${accentColor}\"/>\n"
    "            <circle cx=\"${(history.length - 1) * scaleX}\" cy=\"${height / 2 - history[history.length - 1] * scaleY}\" r=\"4\" fill=\"${accentColor}\"/>\n"
    "            <!-- Popisky -->\n"
    "            <text x=\"5\" y=\"12\" fill=\"#888\" font-size=\"10\" font-weight=\"600\">White</text>\n"
    "            <text x=\"5\" y=\"${height - 2}\" fill=\"#888\" font-size=\"10\" font-weight=\"600\">Black</text>\n"
    "        </svg>`;\n"
    "    }\n"
    "\n"
    "    // Vytvořit nový banner - VLEVO OD BOARDU, NE UPROSTŘED!\n"
    "    const banner = document.createElement('div');\n"
    "    banner.id = 'endgame-banner';\n"
    "\n"
    "    // Na mobilu - jiné umístění (nahoře, plná šířka)\n"
    "    if (window.innerWidth <= 768) {\n"
    "        banner.style.cssText = `\n"
    "            position: fixed;\n"
    "            left: 10px;\n"
    "            right: 10px;\n"
    "            top: 10px;\n"
    "            width: auto;\n"
    "            max-height: 80vh;\n"
    "            transform: none;\n"
    "            overflow-y: auto;\n"
    "            background: ${bgGradient};\n"
    "            border: 2px solid ${accentColor};\n"
    "            border-radius: 12px;\n"
    "            padding: 0;\n"
    "            box-shadow: 0 8px 32px rgba(0,0,0,0.6);\n"
    "            z-index: 9999;\n"
    "            animation: slideInTop 0.4s ease-out;\n"
    "        `;\n"
    "    } else {\n"
    "        banner.style.cssText = `\n"
    "            position: fixed;\n"
    "            left: 10px;\n"
    "            top: 50%;\n"
    "            transform: translateY(-50%);\n"
    "            width: 320px;\n"
    "            max-height: 90vh;\n"
    "            overflow-y: auto;\n"
    "            background: ${bgGradient};\n"
    "            border: 2px solid ${accentColor};\n"
    "            border-radius: 12px;\n"
    "            padding: 0;\n"
    "            box-shadow: 0 8px 32px rgba(0,0,0,0.6), 0 0 40px ${accentColor}40;\n"
    "            z-index: 9999;\n"
    "            animation: slideInLeft 0.4s ease-out;\n"
    "            backdrop-filter: blur(10px);\n"
    "        `;\n"
    "    }\n"
    "\n"
    "    // HTML obsah\n"
    "    banner.innerHTML = `\n"
    "        <div style=\"background:${accentColor};padding:20px;text-align:center;border-radius:10px 10px 0 0;\">\n"
    "            <div style=\"font-size:64px;margin-bottom:8px;\">${emoji}</div>\n"
    "            <h2 style=\"margin:0;color:white;font-size:24px;font-weight:700;text-shadow:0 2px 4px rgba(0,0,0,0.4);\">${title}</h2>\n"
    "            <p style=\"margin:8px 0 0 0;color:rgba(255,255,255,0.9);font-size:14px;font-weight:500;\">${subtitle}</p>\n"
    "        </div>\n"
    "        <div style=\"padding:20px;\">\n"
    "            ${graphSVG ? `\n"
    "            <div style=\"background:rgba(0,0,0,0.3);border-radius:8px;padding:15px;margin-bottom:15px;\">\n"
    "                <h3 style=\"margin:0 0 12px 0;color:${accentColor};font-size:16px;font-weight:600;display:flex;align-items:center;gap:8px;\">\n"
    "                    <span>📈</span> Průběh hry\n"
    "                </h3>\n"
    "                ${graphSVG}\n"
    "                <div style=\"display:flex;justify-content:space-between;margin-top:8px;font-size:11px;color:#888;\">\n"
    "                    <span>Začátek</span>\n"
    "                    <span>Tah ${advantageDataLocal.count || 0}</span>\n"
    "                </div>\n"
    "            </div>` : ''}\n"
    "            <div style=\"background:rgba(0,0,0,0.3);border-radius:8px;padding:15px;margin-bottom:15px;\">\n"
    "                <h3 style=\"margin:0 0 12px 0;color:${accentColor};font-size:16px;font-weight:600;display:flex;align-items:center;gap:8px;\">\n"
    "                    <span>📊</span> Statistiky\n"
    "                </h3>\n"
    "                <div style=\"display:grid;grid-template-columns:1fr 1fr;gap:10px;font-size:13px;\">\n"
    "                    <div style=\"background:rgba(255,255,255,0.05);padding:8px;border-radius:6px;\">\n"
    "                        <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">Tahy</div>\n"
    "                        <div style=\"color:#e0e0e0;font-weight:600;\">⚪ ${whiteMoves} | ⚫ ${blackMoves}</div>\n"
    "                    </div>\n"
    "                    <div style=\"background:rgba(255,255,255,0.05);padding:8px;border-radius:6px;\">\n"
    "                        <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">Materiál</div>\n"
    "                        <div style=\"color:${accentColor};font-weight:600;\">${materialText}</div>\n"
    "                    </div>\n"
    "                    <div style=\"background:rgba(255,255,255,0.05);padding:8px;border-radius:6px;\">\n"
    "                        <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">Sebráno</div>\n"
    "                        <div style=\"color:#e0e0e0;font-weight:600;\">⚪ ${whiteCaptured.length} | ⚫ ${blackCaptured.length}</div>\n"
    "                    </div>\n"
    "                    <div style=\"background:rgba(255,255,255,0.05);padding:8px;border-radius:6px;\">\n"
    "                        <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">Celkem</div>\n"
    "                        <div style=\"color:#e0e0e0;font-weight:600;\">${statusData.move_count} tahů</div>\n"
    "                    </div>\n"
    "                    <div style=\"background:rgba(255,255,255,0.05);padding:8px;border-radius:6px;\">\n"
    "                        <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">Šachy</div>\n"
    "                        <div style=\"color:#e0e0e0;font-weight:600;\">⚪ ${advantageDataLocal.white_checks || 0} | ⚫ ${advantageDataLocal.black_checks || 0}</div>\n"
    "                    </div>\n"
    "                    <div style=\"background:rgba(255,255,255,0.05);padding:8px;border-radius:6px;\">\n"
    "                        <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">Rošády</div>\n"
    "                        <div style=\"color:#e0e0e0;font-weight:600;\">⚪ ${advantageDataLocal.white_castles || 0} | ⚫ ${advantageDataLocal.black_castles || 0}</div>\n"
    "                    </div>\n"
    "                </div>\n"
    "            </div>\n"
    "            <div style=\"background:rgba(0,0,0,0.3);border-radius:8px;padding:15px;margin-bottom:15px;\">\n"
    "                <h3 style=\"margin:0 0 12px 0;color:${accentColor};font-size:16px;font-weight:600;display:flex;align-items:center;gap:8px;\">\n"
    "                    <span>⚔️</span> Sebrané figurky\n"
    "                </h3>\n"
    "                <div style=\"margin-bottom:10px;\">\n"
    "                    <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">White sebral (${whiteCaptured.length})</div>\n"
    "                    <div style=\"font-size:20px;line-height:1.4;\">${whiteCaptured.map(p => pieceSymbols[p] || p).join(' ') || '−'}</div>\n"
    "                </div>\n"
    "                <div>\n"
    "                    <div style=\"color:#888;font-size:11px;margin-bottom:4px;\">Black sebral (${blackCaptured.length})</div>\n"
    "                    <div style=\"font-size:20px;line-height:1.4;\">${blackCaptured.map(p => pieceSymbols[p] || p).join(' ') || '−'}</div>\n"
    "                </div>\n"
    "            </div>\n"
    "            <button onclick=\"hideEndgameReport()\" style=\"\n"
    "                width:100%;\n"
    "                padding:14px;\n"
    "                font-size:16px;\n"
    "                background:${accentColor};\n"
    "                color:white;\n"
    "                border:none;\n"
    "                border-radius:8px;\n"
    "                cursor:pointer;\n"
    "                font-weight:600;\n"
    "                box-shadow:0 4px 12px rgba(0,0,0,0.3);\n"
    "                transition:all 0.2s;\n"
    "            \" onmouseover=\"this.style.transform='translateY(-2px)';this.style.boxShadow='0 6px 16px rgba(0,0,0,0.4)'\" onmouseout=\"this.style.transform='translateY(0)';this.style.boxShadow='0 4px 12px rgba(0,0,0,0.3)'\">\n"
    "                ✓ OK\n"
    "            </button>\n"
    "        </div>\n"
    "    `;\n"
    "\n"
    "    // Přidat CSS animace pokud ještě neexistují\n"
    "    if (!document.getElementById('endgame-animations')) {\n"
    "        const style = document.createElement('style');\n"
    "        style.id = 'endgame-animations';\n"
    "        style.textContent = `\n"
    "            @keyframes slideInLeft {\n"
    "                from { transform: translateY(-50%) translateX(-100%); opacity: 0; }\n"
    "                to { transform: translateY(-50%) translateX(0); opacity: 1; }\n"
    "            }\n"
    "            @keyframes slideInTop {\n"
    "                from { transform: translateY(-100%); opacity: 0; }\n"
    "                to { transform: translateY(0); opacity: 1; }\n"
    "            }\n"
    "        `;\n"
    "        document.head.appendChild(style);\n"
    "    }\n"
    "\n"
    "    document.body.appendChild(banner);\n"
    "    endgameReportShown = true;  // ✅ Označit, že je zobrazený\n"
    "    console.log('🏆 ENDGAME REPORT SHOWN - banner displayed (left side)');\n"
    "}\n"
    "\n"
    "// Skrýt endgame report (ale zachovat flag pro toggle)\n"
    "function hideEndgameReport() {\n"
    "    console.log('Hiding endgame report...');\n"
    "    const banner = document.getElementById('endgame-banner');\n"
    "    if (banner) {\n"
    "        banner.remove();\n"
    "        console.log('Endgame report hidden (can be toggled back)');\n"
    "    }\n"
    "}\n"
    "\n"
    "// Toggle endgame report (show/hide)\n"
    "function toggleEndgameReport() {\n"
    "    const banner = document.getElementById('endgame-banner');\n"
    "    if (banner) {\n"
    "        // Uz je zobrazen -> skryj\n"
    "        hideEndgameReport();\n"
    "    } else {\n"
    "        // Neni zobrazen -> znovu zobraz (pokud mame data)\n"
    "        if (window.lastGameEndData) {\n"
    "            showEndgameReport(window.lastGameEndData);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "// Zobrazit toggle button\n"
    "function showEndgameToggleButton() {\n"
    "    // Zjistit zda uz button existuje\n"
    "    if (document.getElementById('endgame-toggle-btn')) return;\n"
    "\n"
    "    const button = document.createElement('button');\n"
    "    button.id = 'endgame-toggle-btn';\n"
    "    button.innerHTML = '🏆 Report';\n"
    "    button.title = 'Show/Hide Endgame Report';\n"
    "    button.style.cssText = `\n"
    "        position: fixed;\n"
    "        top: 10px;\n"
    "        left: 10px;\n"
    "        padding: 10px 16px;\n"
    "        background: linear-gradient(135deg, #4CAF50, #45a049);\n"
    "        color: white;\n"
    "        border: none;\n"
    "        border-radius: 8px;\n"
    "        cursor: pointer;\n"
    "        font-weight: 600;\n"
    "        font-size: 14px;\n"
    "        box-shadow: 0 4px 12px rgba(0,0,0,0.3);\n"
    "        z-index: 10000;\n"
    "        transition: all 0.2s;\n"
    "    `;\n"
    "    button.onmouseover = function () {\n"
    "        this.style.transform = 'translateY(-2px)';\n"
    "        this.style.boxShadow = '0 6px 16px rgba(0,0,0,0.4)';\n"
    "    };\n"
    "    button.onmouseout = function () {\n"
    "        this.style.transform = 'translateY(0)';\n"
    "        this.style.boxShadow = '0 4px 12px rgba(0,0,0,0.3)';\n"
    "    };\n"
    "    button.onclick = toggleEndgameReport;\n"
    "    document.body.appendChild(button);\n"
    "}\n"
    "\n"
    "// Skrýt toggle button\n"
    "function hideEndgameToggleButton() {\n"
    "    const button = document.getElementById('endgame-toggle-btn');\n"
    "    if (button) {\n"
    "        button.remove();\n"
    "    }\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// STATUS UPDATE FUNCTION\n"
    "// ============================================================================\n"
    "\n"
    "function updateStatus(status) {\n"
    "    statusData = status;\n"
    "    document.getElementById('game-state').textContent = status.game_state || '-';\n"
    "    document.getElementById('current-player').textContent = status.current_player || '-';\n"
    "    document.getElementById('move-count').textContent = status.move_count || 0;\n"
    "    document.getElementById('in-check').textContent = status.in_check ? 'Yes' : 'No';\n"
    "\n"
    "    const lifted = status.piece_lifted;\n"
    "    if (lifted && lifted.lifted) {\n"
    "        document.getElementById('lifted-piece').textContent = pieceSymbols[lifted.piece] || '-';\n"
    "        document.getElementById('lifted-position').textContent = String.fromCharCode(97 + lifted.col) + (lifted.row + 1);\n"
    "        const square = document.querySelector(`[data-row='${lifted.row}'][data-col='${lifted.col}']`);\n"
    "        if (square) square.classList.add('lifted');\n"
    "    } else {\n"
    "        document.getElementById('lifted-piece').textContent = '-';\n"
    "        document.getElementById('lifted-position').textContent = '-';\n"
    "        document.querySelectorAll('.square').forEach(sq => sq.classList.remove('lifted'));\n"
    "    }\n"
    "\n"
    "    // ✅ ENDGAME REPORT - zobrazit pouze JEDNOU, po prvnim skonceni\n"
    "    if (status.game_end && status.game_end.ended) {\n"
    "        // Ulozit data pro pozdejsi toggle\n"
    "        window.lastGameEndData = status.game_end;\n"
    "\n"
    "        // Zobrazit report jen pokud jeste nebyl nikdy zobrazen\n"
    "        if (!endgameReportShown) {\n"
    "            console.log('Game ended, showing endgame report...');\n"
    "            showEndgameReport(status.game_end);\n"
    "        }\n"
    "\n"
    "        // Zobrazit toggle button (jen pokud je hra skoncena)\n"
    "        showEndgameToggleButton();\n"
    "    } else {\n"
    "        // Hra je aktivni - skryj report i toggle button\n"
    "        if (endgameReportShown) {\n"
    "            console.log('Game restarted, clearing endgame report...');\n"
    "            hideEndgameReport();\n"
    "        }\n"
    "        endgameReportShown = false;  // Reset flagu po restartu\n"
    "        window.lastGameEndData = null;\n"
    "        hideEndgameToggleButton();\n"
    "    }\n"
    "\n"
    "}\n"
    "\n"
    "function updateHistory(history) {\n"
    "    historyData = history.moves || [];\n"
    "    const historyBox = document.getElementById('history');\n"
    "    historyBox.innerHTML = '';\n"
    "    historyData.slice().reverse().forEach((move, index) => {\n"
    "        const item = document.createElement('div');\n"
    "        item.className = 'history-item';\n"
    "        const actualIndex = historyData.length - 1 - index;\n"
    "        item.dataset.moveIndex = actualIndex;\n"
    "        const moveNum = Math.floor(actualIndex / 2) + 1;\n"
    "        const isWhite = actualIndex % 2 === 0;\n"
    "        const prefix = isWhite ? moveNum + '. ' : '';\n"
    "        item.textContent = prefix + move.from + ' → ' + move.to;\n"
    "        item.onclick = () => enterReviewMode(actualIndex);\n"
    "        historyBox.appendChild(item);\n"
    "    });\n"
    "}\n"
    "\n"
    "function updateCaptured(captured) {\n"
    "    capturedData = captured;\n"
    "    const whiteBox = document.getElementById('white-captured');\n"
    "    const blackBox = document.getElementById('black-captured');\n"
    "    whiteBox.innerHTML = '';\n"
    "    blackBox.innerHTML = '';\n"
    "    captured.white_captured.forEach(p => {\n"
    "        const piece = document.createElement('div');\n"
    "        piece.className = 'captured-piece';\n"
    "        piece.textContent = pieceSymbols[p] || p;\n"
    "        whiteBox.appendChild(piece);\n"
    "    });\n"
    "    captured.black_captured.forEach(p => {\n"
    "        const piece = document.createElement('div');\n"
    "        piece.className = 'captured-piece';\n"
    "        piece.textContent = pieceSymbols[p] || p;\n"
    "        blackBox.appendChild(piece);\n"
    "    });\n"
    "}\n"
    "\n"
    "async function fetchData() {\n"
    "    if (reviewMode || sandboxMode) return;\n"
    "    try {\n"
    "        const [boardRes, statusRes, historyRes, capturedRes] = await Promise.all([\n"
    "            fetch('/api/board'),\n"
    "            fetch('/api/status'),\n"
    "            fetch('/api/history'),\n"
    "            fetch('/api/captured')\n"
    "        ]);\n"
    "        const board = await boardRes.json();\n"
    "        const status = await statusRes.json();\n"
    "        const history = await historyRes.json();\n"
    "        const captured = await capturedRes.json();\n"
    "        updateBoard(board.board);\n"
    "        updateStatus(status);\n"
    "        updateHistory(history);\n"
    "        updateCaptured(captured);\n"
    "    } catch (error) {\n"
    "        console.error('Fetch error:', error);\n"
    "    }\n"
    "}\n"
    "\n"
    "function initializeApp() {\n"
    "    console.log('🎮 Initializing Chess App...');\n"
    "    createBoard();\n"
    "\n"
    "    // Inject Demo Mode section at bottom\n"
    "    injectDemoModeSection();\n"
    "\n"
    "    fetchBoardData();\n"
    "    setInterval(fetchBoardData, 500);\n"
    "    console.log('✅ Chess App initialized');\n"
    "}\n"
    "\n"
    "/**\n"
    " * Inject Demo Mode control section into DOM\n"
    " * Placed at bottom, below all main content\n"
    " */\n"
    "function injectDemoModeSection() {\n"
    "    const container = document.querySelector('.container') || document.body;\n"
    "\n"
    "    const demoSection = document.createElement('div');\n"
    "    demoSection.style.cssText = 'margin-top:30px; padding:20px; background:#2a2a2a; border-radius:8px; border-left:4px solid #666;';\n"
    "    demoSection.innerHTML = `\n"
    "        <h3 style=\"color:#999;font-size:0.9em;margin-bottom:15px;text-transform:uppercase;letter-spacing:1px;\">🤖 Demo Mode</h3>\n"
    "        <div style=\"display:flex;align-items:center;gap:15px;margin-bottom:10px;\">\n"
    "            <button id=\"btnDemoMode\" onclick=\"toggleDemoMode()\" \n"
    "                    style=\"padding:10px 20px;background:#008CBA;color:white;border:2px solid #007396;\n"
    "                           border-radius:6px;cursor:pointer;font-size:14px;font-weight:600;transition:all 0.3s;\">\n"
    "                Toggle Demo Mode\n"
    "            </button>\n"
    "            <span id=\"demoStatus\" style=\"font-size:14px;color:#999;\">⚫ Off</span>\n"
    "        </div>\n"
    "        <p style=\"font-size:12px;color:#666;margin:0;font-style:italic;\">\n"
    "            Automatic chess game playback. Touch board to interrupt.\n"
    "        </p>\n"
    "    `;\n"
    "\n"
    "    container.appendChild(demoSection);\n"
    "    console.log('✅ Demo Mode section injected');\n"
    "}\n"
    "\n"
    "console.log('🚀 Creating chess board...');\n"
    "initializeApp(); // Call the new initialization function\n"
    "console.log('✅ Chess JavaScript loaded successfully!');\n"
    "console.log('⏱️ About to initialize timer system...');\n"
    "\n"
    "// ============================================================================\n"
    "// TIMER SYSTEM\n"
    "// ============================================================================\n"
    "\n"
    "let timerData = {\n"
    "    white_time_ms: 0,\n"
    "    black_time_ms: 0,\n"
    "    timer_running: false,\n"
    "    is_white_turn: true,\n"
    "    game_paused: false,\n"
    "    time_expired: false,\n"
    "    config: null,\n"
    "    total_moves: 0,\n"
    "    avg_move_time_ms: 0\n"
    "};\n"
    "let timerUpdateInterval = null;\n"
    "let selectedTimeControl = 0;\n"
    "\n"
    "// ========== HELPER FUNCTIONS (must be defined before use) ==========\n"
    "\n"
    "function formatTime(timeMs) {\n"
    "    const totalSeconds = Math.ceil(timeMs / 1000);\n"
    "    const hours = Math.floor(totalSeconds / 3600);\n"
    "    const minutes = Math.floor((totalSeconds % 3600) / 60);\n"
    "    const seconds = totalSeconds % 60;\n"
    "    if (hours > 0) {\n"
    "        return hours + ':' + minutes.toString().padStart(2, '0') + ':' + seconds.toString().padStart(2, '0');\n"
    "    } else {\n"
    "        return minutes + ':' + seconds.toString().padStart(2, '0');\n"
    "    }\n"
    "}\n"
    "\n"
    "function updatePlayerTime(player, timeMs) {\n"
    "    const timeElement = document.getElementById(player + '-time');\n"
    "    const playerElement = document.getElementById(player + '-timer');\n"
    "    if (!timeElement || !playerElement) return;\n"
    "\n"
    "    // Zkontrolovat zda je časová kontrola aktivní\n"
    "    const isTimerActive = timerData.config && timerData.config.type !== 0;\n"
    "\n"
    "    if (isTimerActive) {\n"
    "        const formattedTime = formatTime(timeMs);\n"
    "        timeElement.textContent = formattedTime;\n"
    "        playerElement.classList.remove('low-time', 'critical-time');\n"
    "        if (timeMs < 5000) playerElement.classList.add('critical-time');\n"
    "        else if (timeMs < 30000) playerElement.classList.add('low-time');\n"
    "    } else {\n"
    "        // Bez časové kontroly - zobrazit \"--:--\" a odstranit všechny warning třídy\n"
    "        timeElement.textContent = '--:--';\n"
    "        playerElement.classList.remove('low-time', 'critical-time', 'active');\n"
    "        return; // Nedělat nic dalšího\n"
    "    }\n"
    "\n"
    "    if ((player === 'white' && timerData.is_white_turn) || (player === 'black' && !timerData.is_white_turn)) {\n"
    "        playerElement.classList.add('active');\n"
    "    } else {\n"
    "        playerElement.classList.remove('active');\n"
    "    }\n"
    "}\n"
    "\n"
    "function updateActivePlayer(isWhiteTurn) {\n"
    "    const whiteIndicator = document.getElementById('white-move-indicator');\n"
    "    const blackIndicator = document.getElementById('black-move-indicator');\n"
    "    if (whiteIndicator && blackIndicator) {\n"
    "        whiteIndicator.classList.toggle('active', isWhiteTurn);\n"
    "        blackIndicator.classList.toggle('active', !isWhiteTurn);\n"
    "    }\n"
    "}\n"
    "\n"
    "function updateProgressBars(timerInfo) {\n"
    "    if (!timerInfo || !timerInfo.config) {\n"
    "        console.warn('Timer info missing config:', timerInfo);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    // Zkontrolovat zda je časová kontrola aktivní\n"
    "    if (timerInfo.config.type === 0) {\n"
    "        // Bez časové kontroly - skrýt progress bary\n"
    "        const whiteProgress = document.getElementById('white-progress');\n"
    "        const blackProgress = document.getElementById('black-progress');\n"
    "        if (whiteProgress) whiteProgress.style.width = '0%';\n"
    "        if (blackProgress) blackProgress.style.width = '0%';\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    const initialTime = timerInfo.config.initial_time_ms;\n"
    "    if (initialTime === 0) return;\n"
    "    const whiteProgress = document.getElementById('white-progress');\n"
    "    const blackProgress = document.getElementById('black-progress');\n"
    "    if (whiteProgress) {\n"
    "        const whitePercent = (timerInfo.white_time_ms / initialTime) * 100;\n"
    "        whiteProgress.style.width = Math.max(0, Math.min(100, whitePercent)) + '%';\n"
    "    }\n"
    "    if (blackProgress) {\n"
    "        const blackPercent = (timerInfo.black_time_ms / initialTime) * 100;\n"
    "        blackProgress.style.width = Math.max(0, Math.min(100, blackPercent)) + '%';\n"
    "    }\n"
    "}\n"
    "\n"
    "function updateTimerStats(timerInfo) {\n"
    "    const avgMoveTimeElement = document.getElementById('avg-move-time');\n"
    "    const totalMovesElement = document.getElementById('total-moves');\n"
    "    if (avgMoveTimeElement) {\n"
    "        avgMoveTimeElement.textContent = timerInfo.avg_move_time_ms > 0 ? formatTime(timerInfo.avg_move_time_ms) : '-';\n"
    "    }\n"
    "    if (totalMovesElement) {\n"
    "        totalMovesElement.textContent = timerInfo.total_moves || 0;\n"
    "    }\n"
    "}\n"
    "\n"
    "function checkTimeWarnings(timerInfo) {\n"
    "    // Nekontrolovat upozornění pokud není časová kontrola aktivní\n"
    "    if (!timerInfo || !timerInfo.config || timerInfo.config.type === 0) {\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    const currentPlayerTime = timerInfo.is_white_turn ? timerInfo.white_time_ms : timerInfo.black_time_ms;\n"
    "    if (currentPlayerTime < 5000 && !timerInfo.warning_5s_shown) {\n"
    "        showTimeWarning('Critical! Less than 5 seconds!', 'critical');\n"
    "    } else if (currentPlayerTime < 10000 && !timerInfo.warning_10s_shown) {\n"
    "        showTimeWarning('Warning! Less than 10 seconds!', 'warning');\n"
    "    } else if (currentPlayerTime < 30000 && !timerInfo.warning_30s_shown) {\n"
    "        showTimeWarning('Low time! Less than 30 seconds!', 'info');\n"
    "    }\n"
    "}\n"
    "\n"
    "function showTimeWarning(message, type) {\n"
    "    const notification = document.createElement('div');\n"
    "    notification.className = 'time-warning ' + type;\n"
    "    notification.textContent = message;\n"
    "    notification.style.cssText = 'position: fixed; top: 20px; right: 20px; padding: 15px 20px; border-radius: 8px; color: white; font-weight: 600; z-index: 1000; animation: slideInRight 0.3s ease;';\n"
    "    switch (type) {\n"
    "        case 'critical': notification.style.background = '#F44336'; break;\n"
    "        case 'warning': notification.style.background = '#FF9800'; break;\n"
    "        case 'info': notification.style.background = '#2196F3'; break;\n"
    "    }\n"
    "    document.body.appendChild(notification);\n"
    "    setTimeout(() => {\n"
    "        notification.style.animation = 'slideOutRight 0.3s ease';\n"
    "        setTimeout(() => {\n"
    "            if (notification.parentNode) notification.parentNode.removeChild(notification);\n"
    "        }, 300);\n"
    "    }, 3000);\n"
    "}\n"
    "\n"
    "function handleTimeExpiration(timerInfo) {\n"
    "    // Nekontrolovat expiraci pokud není časová kontrola aktivní\n"
    "    if (!timerInfo || !timerInfo.config || timerInfo.config.type === 0) {\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    const expiredPlayer = timerInfo.is_white_turn ? 'White' : 'Black';\n"
    "    showTimeWarning('Time expired! ' + expiredPlayer + ' lost on time.', 'critical');\n"
    "    const pauseBtn = document.getElementById('pause-timer');\n"
    "    const resumeBtn = document.getElementById('resume-timer');\n"
    "    if (pauseBtn) pauseBtn.disabled = true;\n"
    "    if (resumeBtn) resumeBtn.disabled = true;\n"
    "}\n"
    "\n"
    "function toggleCustomSettings() {\n"
    "    const customSettings = document.getElementById('custom-time-settings');\n"
    "    if (!customSettings) return;\n"
    "    if (selectedTimeControl === 14) {\n"
    "        customSettings.style.display = 'block';\n"
    "    } else {\n"
    "        customSettings.style.display = 'none';\n"
    "    }\n"
    "}\n"
    "\n"
    "function changeTimeControl() {\n"
    "    const select = document.getElementById('time-control-select');\n"
    "    const applyBtn = document.getElementById('apply-time-control');\n"
    "    if (!select) return;\n"
    "    selectedTimeControl = parseInt(select.value);\n"
    "    toggleCustomSettings();\n"
    "    if (applyBtn) applyBtn.disabled = false;\n"
    "    localStorage.setItem('chess_time_control', selectedTimeControl.toString());\n"
    "}\n"
    "\n"
    "// ========== TIMER INITIALIZATION AND MAIN FUNCTIONS ==========\n"
    "\n"
    "function initTimerSystem() {\n"
    "    console.log('🔵 Initializing timer system...');\n"
    "    // Check if DOM elements exist before accessing them\n"
    "    const timeControlSelect = document.getElementById('time-control-select');\n"
    "    const applyButton = document.getElementById('apply-time-control');\n"
    "    if (!timeControlSelect) {\n"
    "        console.warn('⚠️ Timer controls not ready yet, retrying in 100ms...');\n"
    "        setTimeout(() => initTimerSystem(), 100);\n"
    "        return;\n"
    "    }\n"
    "    const savedTimeControl = localStorage.getItem('chess_time_control');\n"
    "    if (savedTimeControl) {\n"
    "        selectedTimeControl = parseInt(savedTimeControl);\n"
    "        timeControlSelect.value = selectedTimeControl;\n"
    "    } else {\n"
    "        selectedTimeControl = parseInt(timeControlSelect.value);\n"
    "    }\n"
    "    toggleCustomSettings();\n"
    "    // Enable button if a time control is selected (not 0 = None)\n"
    "    if (selectedTimeControl !== 0 && applyButton) {\n"
    "        applyButton.disabled = false;\n"
    "    }\n"
    "    console.log('🔵 Starting timer update loop immediately...');\n"
    "    // Start timer loop immediately (no delay)\n"
    "    startTimerUpdateLoop();\n"
    "}\n"
    "\n"
    "function startTimerUpdateLoop() {\n"
    "    console.log('✅ Timer update loop starting... (will update every 300ms)');\n"
    "    if (timerUpdateInterval) {\n"
    "        console.log('⚠️ Clearing existing timer interval');\n"
    "        clearInterval(timerUpdateInterval);\n"
    "    }\n"
    "    timerUpdateInterval = setInterval(async () => {\n"
    "        try {\n"
    "            await updateTimerDisplay();\n"
    "        } catch (error) {\n"
    "            console.error('❌ Timer update loop error:', error);\n"
    "        }\n"
    "    }, 200);\n"
    "    console.log('✅ Timer interval set successfully, ID:', timerUpdateInterval);\n"
    "    // Initial immediate update\n"
    "    console.log('⏱️ Calling initial timer update...');\n"
    "    updateTimerDisplay().catch(e => console.error('❌ Initial timer update failed:', e));\n"
    "}\n"
    "\n"
    "async function updateTimerDisplay() {\n"
    "    try {\n"
    "        console.log('⏱️ updateTimerDisplay() called, fetching /api/timer...');\n"
    "        const response = await fetch('/api/timer');\n"
    "        console.log('⏱️ /api/timer response status:', response.status);\n"
    "        if (response.ok) {\n"
    "            const timerInfo = await response.json();\n"
    "            timerData = timerInfo;\n"
    "            // Format time for logging\n"
    "            const whiteTime = formatTime(timerInfo.white_time_ms);\n"
    "            const blackTime = formatTime(timerInfo.black_time_ms);\n"
    "            console.log('⏱️ Timer:', timerInfo.config ? timerInfo.config.name : 'NO CONFIG', '| White:', whiteTime, '(' + timerInfo.white_time_ms + 'ms)', '| Black:', blackTime, '(' + timerInfo.black_time_ms + 'ms)');\n"
    "            updatePlayerTime('white', timerInfo.white_time_ms);\n"
    "            updatePlayerTime('black', timerInfo.black_time_ms);\n"
    "            updateActivePlayer(timerInfo.is_white_turn);\n"
    "            updateProgressBars(timerInfo);\n"
    "            updateTimerStats(timerInfo);\n"
    "            // Disable/enable timer controls podle config.type\n"
    "            const pauseBtn = document.getElementById('pause-timer');\n"
    "            const resumeBtn = document.getElementById('resume-timer');\n"
    "            const resetBtn = document.getElementById('reset-timer');\n"
    "            const isTimerActive = timerInfo.config && timerInfo.config.type !== 0;\n"
    "            if (pauseBtn) pauseBtn.disabled = !isTimerActive;\n"
    "            if (resumeBtn) resumeBtn.disabled = !isTimerActive;\n"
    "            if (resetBtn) resetBtn.disabled = !isTimerActive;\n"
    "            // Pouze pokud je časová kontrola aktivní\n"
    "            if (isTimerActive) {\n"
    "                checkTimeWarnings(timerInfo);\n"
    "                if (timerInfo.time_expired) {\n"
    "                    handleTimeExpiration(timerInfo);\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            console.error('❌ Timer update failed:', response.status);\n"
    "        }\n"
    "    } catch (error) {\n"
    "        console.error('❌ Timer update error:', error);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function applyTimeControl() {\n"
    "    const timeControlSelect = document.getElementById('time-control-select');\n"
    "    const timeControlType = parseInt(timeControlSelect.value);\n"
    "    let config = { type: timeControlType };\n"
    "    if (timeControlType === 14) {\n"
    "        const minutes = parseInt(document.getElementById('custom-minutes').value);\n"
    "        const increment = parseInt(document.getElementById('custom-increment').value);\n"
    "        if (minutes < 1 || minutes > 180) { alert('Minutes must be between 1 and 180'); return; }\n"
    "        if (increment < 0 || increment > 60) { alert('Increment must be between 0 and 60 seconds'); return; }\n"
    "        config.custom_minutes = minutes;\n"
    "        config.custom_increment = increment;\n"
    "    }\n"
    "    try {\n"
    "        console.log('Applying time control:', config);\n"
    "        const response = await fetch('/api/timer/config', {\n"
    "            method: 'POST',\n"
    "            headers: { 'Content-Type': 'application/json' },\n"
    "            body: JSON.stringify(config)\n"
    "        });\n"
    "        if (response.ok) {\n"
    "            const responseText = await response.text();\n"
    "            console.log('✅ Time control response:', responseText);\n"
    "            // Wait for backend to process the command\n"
    "            await new Promise(resolve => setTimeout(resolve, 500));\n"
    "            // Refresh timer display multiple times to ensure update\n"
    "            for (let i = 0; i < 5; i++) {\n"
    "                await updateTimerDisplay();\n"
    "                await new Promise(resolve => setTimeout(resolve, 300));\n"
    "            }\n"
    "            showTimeWarning('Time control applied!', 'info');\n"
    "            const applyBtn = document.getElementById('apply-time-control');\n"
    "            if (applyBtn) applyBtn.disabled = true;\n"
    "        } else {\n"
    "            const errorText = await response.text();\n"
    "            console.error('Failed to apply time control:', response.status, errorText);\n"
    "            throw new Error('Failed to apply time control: ' + errorText);\n"
    "        }\n"
    "    } catch (error) {\n"
    "        console.error('Error applying time control:', error);\n"
    "        showTimeWarning('Error setting time control: ' + error.message, 'critical');\n"
    "    }\n"
    "}\n"
    "\n"
    "async function pauseTimer() {\n"
    "    try {\n"
    "        const response = await fetch('/api/timer/pause', { method: 'POST' });\n"
    "        if (response.ok) {\n"
    "            const pauseBtn = document.getElementById('pause-timer');\n"
    "            const resumeBtn = document.getElementById('resume-timer');\n"
    "            if (pauseBtn) pauseBtn.style.display = 'none';\n"
    "            if (resumeBtn) resumeBtn.style.display = 'inline-block';\n"
    "            showTimeWarning('Timer paused', 'info');\n"
    "        }\n"
    "    } catch (error) {\n"
    "        console.error('❌ Error pausing timer:', error);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function resumeTimer() {\n"
    "    try {\n"
    "        const response = await fetch('/api/timer/resume', { method: 'POST' });\n"
    "        if (response.ok) {\n"
    "            const pauseBtn = document.getElementById('pause-timer');\n"
    "            const resumeBtn = document.getElementById('resume-timer');\n"
    "            if (pauseBtn) pauseBtn.style.display = 'inline-block';\n"
    "            if (resumeBtn) resumeBtn.style.display = 'none';\n"
    "            showTimeWarning('Timer resumed', 'info');\n"
    "        }\n"
    "    } catch (error) {\n"
    "        console.error('❌ Error resuming timer:', error);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function resetTimer() {\n"
    "    if (confirm('Really reset timer?')) {\n"
    "        try {\n"
    "            const response = await fetch('/api/timer/reset', { method: 'POST' });\n"
    "            if (response.ok) {\n"
    "                showTimeWarning('Timer reset', 'info');\n"
    "                console.log('✅ Timer reset successfully');\n"
    "                await updateTimerDisplay();\n"
    "            }\n"
    "        } catch (error) {\n"
    "            console.error('❌ Error resetting timer:', error);\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "// Expose timer functions globally for inline onclick handlers\n"
    "window.changeTimeControl = changeTimeControl;\n"
    "window.applyTimeControl = applyTimeControl;\n"
    "window.pauseTimer = pauseTimer;\n"
    "window.resumeTimer = resumeTimer;\n"
    "window.resetTimer = resetTimer;\n"
    "window.hideEndgameReport = hideEndgameReport;\n"
    "\n"
    "// Initialize timer system immediately (will retry if DOM not ready)\n"
    "console.log('⏱️ Exposing timer functions and calling initTimerSystem()...');\n"
    "try {\n"
    "    initTimerSystem();\n"
    "    console.log('✅ initTimerSystem() called successfully');\n"
    "} catch (error) {\n"
    "    console.error('❌ CRITICAL ERROR in initTimerSystem():', error);\n"
    "    console.error('Stack:', error.stack);\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// KEYBOARD SHORTCUTS AND EVENT HANDLERS\n"
    "// ============================================================================\n"
    "\n"
    "document.addEventListener('keydown', (e) => {\n"
    "    if (e.key === 'Escape') {\n"
    "        if (reviewMode) {\n"
    "            exitReviewMode();\n"
    "        } else if (sandboxMode) {\n"
    "            exitSandboxMode();\n"
    "        } else {\n"
    "            clearHighlights();\n"
    "        }\n"
    "    }\n"
    "    if (historyData.length === 0) return;\n"
    "    switch (e.key) {\n"
    "        case 'ArrowLeft':\n"
    "            e.preventDefault();\n"
    "            if (reviewMode && currentReviewIndex > 0) {\n"
    "                enterReviewMode(currentReviewIndex - 1);\n"
    "            } else if (!reviewMode && !sandboxMode && historyData.length > 0) {\n"
    "                enterReviewMode(historyData.length - 1);\n"
    "            }\n"
    "            break;\n"
    "        case 'ArrowRight':\n"
    "            e.preventDefault();\n"
    "            if (reviewMode && currentReviewIndex < historyData.length - 1) {\n"
    "                enterReviewMode(currentReviewIndex + 1);\n"
    "            }\n"
    "            break;\n"
    "    }\n"
    "});\n"
    "\n"
    "// Click outside to deselect\n"
    "document.addEventListener('click', (e) => {\n"
    "    if (!e.target.closest('.square') && !e.target.closest('.history-item')) {\n"
    "        if (!reviewMode) {\n"
    "            clearHighlights();\n"
    "        }\n"
    "    }\n"
    "});\n"
    "\n"
    "// ============================================================================\n"
    "// WIFI FUNCTIONS\n"
    "// ============================================================================\n"
    "\n"
    "async function saveWiFiConfig() {\n"
    "    const ssid = document.getElementById('wifi-ssid').value;\n"
    "    const password = document.getElementById('wifi-password').value;\n"
    "    if (!ssid || !password) {\n"
    "        alert('SSID and password are required');\n"
    "        return;\n"
    "    }\n"
    "    try {\n"
    "        const response = await fetch('/api/wifi/config', {\n"
    "            method: 'POST',\n"
    "            headers: { 'Content-Type': 'application/json' },\n"
    "            body: JSON.stringify({ ssid: ssid, password: password })\n"
    "        });\n"
    "        const data = await response.json();\n"
    "        if (data.success) {\n"
    "            alert('WiFi config saved. Now press \"Connect STA\".');\n"
    "        } else {\n"
    "            alert('Failed to save WiFi config: ' + data.message);\n"
    "        }\n"
    "    } catch (error) {\n"
    "        alert('Error: ' + error.message);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function connectSTA() {\n"
    "    try {\n"
    "        const response = await fetch('/api/wifi/connect', { method: 'POST' });\n"
    "        const data = await response.json();\n"
    "        if (data.success) {\n"
    "            alert('Connecting to WiFi...');\n"
    "            setTimeout(updateWiFiStatus, 1500);\n"
    "        } else {\n"
    "            alert('Failed to connect: ' + data.message);\n"
    "        }\n"
    "    } catch (error) {\n"
    "        alert('Error: ' + error.message);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function disconnectSTA() {\n"
    "    try {\n"
    "        const response = await fetch('/api/wifi/disconnect', { method: 'POST' });\n"
    "        const data = await response.json();\n"
    "        if (data.success) {\n"
    "            alert('Disconnected from WiFi');\n"
    "            setTimeout(updateWiFiStatus, 1000);\n"
    "        } else {\n"
    "            alert('Failed to disconnect: ' + data.message);\n"
    "        }\n"
    "    } catch (error) {\n"
    "        alert('Error: ' + error.message);\n"
    "    }\n"
    "}\n"
    "\n"
    "async function updateWiFiStatus() {\n"
    "    try {\n"
    "        const response = await fetch('/api/wifi/status');\n"
    "        const data = await response.json();\n"
    "        document.getElementById('ap-ssid').textContent = data.ap_ssid || 'ESP32-CzechMate';\n"
    "        document.getElementById('ap-ip').textContent = data.ap_ip || '192.168.4.1';\n"
    "        document.getElementById('ap-clients').textContent = data.ap_clients || 0;\n"
    "        document.getElementById('sta-ssid').textContent = data.sta_ssid || 'Not configured';\n"
    "        document.getElementById('sta-ip').textContent = data.sta_ip || 'Not connected';\n"
    "        document.getElementById('sta-connected').textContent = data.sta_connected ? 'true' : 'false';\n"
    "        if (data.sta_ssid && data.sta_ssid !== 'Not configured') {\n"
    "            document.getElementById('wifi-ssid').value = data.sta_ssid;\n"
    "        }\n"
    "    } catch (error) {\n"
    "        console.error('Failed to update WiFi status:', error);\n"
    "    }\n"
    "}\n"
    "\n"
    "// Expose WiFi functions globally for inline onclick handlers\n"
    "window.saveWiFiConfig = saveWiFiConfig;\n"
    "window.connectSTA = connectSTA;\n"
    "window.disconnectSTA = disconnectSTA;\n"
    "\n"
    "// Start WiFi status update loop (every 5 seconds)\n"
    "let wifiStatusInterval = null;\n"
    "function startWiFiStatusUpdateLoop() {\n"
    "    if (wifiStatusInterval) {\n"
    "        clearInterval(wifiStatusInterval);\n"
    "    }\n"
    "    // Initial update\n"
    "    updateWiFiStatus();\n"
    "    // Update every 5 seconds\n"
    "    wifiStatusInterval = setInterval(updateWiFiStatus, 5000);\n"
    "}\n"
    "\n"
    "// Start WiFi status updates when DOM is ready\n"
    "if (document.readyState === 'loading') {\n"
    "    document.addEventListener('DOMContentLoaded', startWiFiStatusUpdateLoop);\n"
    "} else {\n"
    "    startWiFiStatusUpdateLoop();\n"
    "}\n"
    "\n"
    "// ============================================================================\n"
    "// DEMO MODE (SCREENSAVER) FUNCTIONS\n"
    "// ============================================================================\n"
    "\n"
    "/**\n"
    " * Toggle demo/screensaver mode on or off\n"
    " */\n"
    "async function toggleDemoMode() {\n"
    "    try {\n"
    "        // Get current state\n"
    "        const currentlyEnabled = await isDemoModeEnabled();\n"
    "        const newState = !currentlyEnabled;\n"
    "\n"
    "        // Send toggle request\n"
    "        const response = await fetch('/api/demo/config', {\n"
    "            method: 'POST',\n"
    "            headers: { 'Content-Type': 'application/json' },\n"
    "            body: JSON.stringify({ enabled: newState })\n"
    "        });\n"
    "\n"
    "        const data = await response.json();\n"
    "\n"
    "        if (data.success) {\n"
    "            console.log('✅ Demo mode toggled:', newState ? 'ON' : 'OFF');\n"
    "            // Update status immediately\n"
    "            await updateDemoModeStatus();\n"
    "        } else {\n"
    "            console.error('❌ Failed to toggle demo mode');\n"
    "            alert('Failed to toggle demo mode: ' + (data.message || 'Unknown error'));\n"
    "        }\n"
    "    } catch (error) {\n"
    "        console.error('Error toggling demo mode:', error);\n"
    "        alert('Error toggling demo mode');\n"
    "    }\n"
    "}\n"
    "\n"
    "/**\n"
    " * Check if demo mode is currently enabled\n"
    " * @returns {Promise<boolean>} True if enabled\n"
    " */\n"
    "async function isDemoModeEnabled() {\n"
    "    try {\n"
    "        const response = await fetch('/api/demo/status');\n"
    "        const data = await response.json();\n"
    "        return data.enabled === true;\n"
    "    } catch (error) {\n"
    "        console.error('Failed to check demo mode status:', error);\n"
    "        return false;\n"
    "    }\n"
    "}\n"
    "\n"
    "/**\n"
    " * Update demo mode status indicator in UI\n"
    " */\n"
    "async function updateDemoModeStatus() {\n"
    "    try {\n"
    "        const enabled = await isDemoModeEnabled();\n"
    "        const statusEl = document.getElementById('demoStatus');\n"
    "        const btnEl = document.getElementById('btnDemoMode');\n"
    "\n"
    "        if (statusEl) {\n"
    "            if (enabled) {\n"
    "                statusEl.textContent = '🟢 Active';\n"
    "                statusEl.style.color = '#4CAF50';\n"
    "                statusEl.style.fontWeight = 'bold';\n"
    "            } else {\n"
    "                statusEl.textContent = '⚫ Off';\n"
    "                statusEl.style.color = '#999';\n"
    "                statusEl.style.fontWeight = 'normal';\n"
    "            }\n"
    "        }\n"
    "\n"
    "        if (btnEl) {\n"
    "            if (enabled) {\n"
    "                btnEl.classList.add('btn-active');\n"
    "                btnEl.style.backgroundColor = '#4CAF50';\n"
    "                btnEl.style.borderColor = '#45a049';\n"
    "            } else {\n"
    "                btnEl.classList.remove('btn-active');\n"
    "                btnEl.style.backgroundColor = '#008CBA';\n"
    "                btnEl.style.borderColor = '#007396';\n"
    "            }\n"
    "        }\n"
    "    } catch (error) {\n"
    "        console.error('Failed to update demo mode status:', error);\n"
    "    }\n"
    "}\n"
    "\n"
    "// Expose demo mode functions globally\n"
    "window.toggleDemoMode = toggleDemoMode;\n"
    "window.updateDemoModeStatus = updateDemoModeStatus;\n"
    "\n"
    "// Start demo mode status update loop (every 3 seconds)\n"
    "let demoModeStatusInterval = null;\n"
    "function startDemoModeStatusUpdateLoop() {\n"
    "    if (demoModeStatusInterval) {\n"
    "        clearInterval(demoModeStatusInterval);\n"
    "    }\n"
    "    // Initial update\n"
    "    updateDemoModeStatus();\n"
    "    // Update every 3 seconds\n"
    "    demoModeStatusInterval = setInterval(updateDemoModeStatus, 3000);\n"
    "}\n"
    "\n"
    "// Start demo mode status updates when DOM is ready\n"
    "if (document.readyState === 'loading') {\n"
    "    document.addEventListener('DOMContentLoaded', startDemoModeStatusUpdateLoop);\n"
    "} else {\n"
    "    startDemoModeStatusUpdateLoop();\n"
    "}\n"
    "\n";
