// ============================================================================
// OPENING CATALOG — generated by tools/openings/sync_catalog.py --copy
// ============================================================================
(function (global) {
    'use strict';

    /** @type {Array<object>} */
    var OPENING_LINES = [
    {
        "id": "italian_giuoco_white",
        "eco": "C50",
        "name": {
            "cs": "Italská hra — Giuoco Piano",
            "en": "Italian Game — Giuoco Piano"
        },
        "side": "white",
        "difficulty": 2,
        "idea": {
            "cs": "Rychlý rozvoj a tlak na f7.",
            "en": "Rapid development and pressure on f7."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "e7e5",
            "g1f3",
            "b8c6",
            "f1c4",
            "f8c5",
            "c2c3",
            "g8f6"
        ],
        "player_ply_indices": [
            0,
            2,
            4,
            6
        ],
        "checkpoint_ply_indices": [
            4
        ],
        "mirror_line_id": "sicilian_odb_black"
    },
    {
        "id": "sicilian_odb_black",
        "eco": "B50",
        "name": {
            "cs": "Sicilská — ODB (úvod)",
            "en": "Sicilian — Open Defence intro"
        },
        "side": "black",
        "difficulty": 2,
        "idea": {
            "cs": "Asymetrická hra proti 1.e4.",
            "en": "Asymmetric play against 1.e4."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "c7c5",
            "g1f3",
            "d7d6",
            "d2d4",
            "g8f6",
            "b1c3",
            "a7a6"
        ],
        "player_ply_indices": [
            1,
            3,
            5,
            7
        ],
        "checkpoint_ply_indices": [
            3
        ],
        "mirror_line_id": "italian_giuoco_white"
    },
    {
        "id": "london_system_white",
        "eco": "D02",
        "name": {
            "cs": "Londýnský systém",
            "en": "London System"
        },
        "side": "white",
        "difficulty": 1,
        "idea": {
            "cs": "Solidní systém s Bf4 a e3.",
            "en": "Solid system with Bf4 and e3."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "d2d4",
            "d7d5",
            "c1f4",
            "g8f6",
            "e2e3",
            "e7e6",
            "g1f3",
            "f8d6"
        ],
        "player_ply_indices": [
            0,
            2,
            4,
            6
        ],
        "checkpoint_ply_indices": [
            4
        ]
    },
    {
        "id": "four_knights_white",
        "eco": "C47",
        "name": {
            "cs": "Čtyři jezdci",
            "en": "Four Knights Game"
        },
        "side": "white",
        "difficulty": 1,
        "idea": {
            "cs": "Rychlý a symetrický rozvoj figur.",
            "en": "Quick symmetrical piece development."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "e7e5",
            "g1f3",
            "b8c6",
            "b1c3",
            "g8f6",
            "f1b5",
            "f8b4"
        ],
        "player_ply_indices": [
            0,
            2,
            4,
            6
        ],
        "checkpoint_ply_indices": [
            4
        ]
    },
    {
        "id": "vienna_white",
        "eco": "C25",
        "name": {
            "cs": "Vídeňská hra",
            "en": "Vienna Game"
        },
        "side": "white",
        "difficulty": 2,
        "idea": {
            "cs": "Jezdec c3 a fianchetto královského střelce.",
            "en": "Nc3 and a kingside bishop fianchetto."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "e7e5",
            "b1c3",
            "b8c6",
            "g2g3",
            "g8f6",
            "f1g2",
            "f8c5"
        ],
        "player_ply_indices": [
            0,
            2,
            4,
            6
        ],
        "checkpoint_ply_indices": [
            4
        ]
    },
    {
        "id": "spanish_berlin_white",
        "eco": "C60",
        "name": {
            "cs": "Španělská — Berlin",
            "en": "Ruy Lopez — Berlin Defence"
        },
        "side": "white",
        "difficulty": 3,
        "idea": {
            "cs": "Tlak střelce b5 na jezdce c6.",
            "en": "Bb5 pressure on the Nc6 knight."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "e7e5",
            "g1f3",
            "b8c6",
            "f1b5",
            "g8f6"
        ],
        "player_ply_indices": [
            0,
            2,
            4
        ],
        "checkpoint_ply_indices": [
            4
        ]
    },
    {
        "id": "queens_gambit_white",
        "eco": "D06",
        "name": {
            "cs": "Dámský gambit — přijatý",
            "en": "Queen's Gambit Accepted intro"
        },
        "side": "white",
        "difficulty": 2,
        "idea": {
            "cs": "Centrum d4 a rozvoj lehkých figur.",
            "en": "d4 center and light-piece development."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "d2d4",
            "d7d5",
            "c2c4",
            "e7e6",
            "b1c3",
            "g8f6",
            "g1f3",
            "b8d7"
        ],
        "player_ply_indices": [
            0,
            2,
            4,
            6
        ],
        "checkpoint_ply_indices": [
            4
        ]
    },
    {
        "id": "caro_kann_classical_black",
        "eco": "B12",
        "name": {
            "cs": "Caro-Kann — klasická",
            "en": "Caro-Kann — Classical"
        },
        "side": "black",
        "difficulty": 2,
        "idea": {
            "cs": "Solidní c6 a d5 proti 1.e4.",
            "en": "Solid c6 and ...d5 against 1.e4."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "c7c6",
            "d2d4",
            "d7d5",
            "b1c3",
            "e7e6",
            "g1f3",
            "g8f6"
        ],
        "player_ply_indices": [
            1,
            3,
            5,
            7
        ],
        "checkpoint_ply_indices": [
            3
        ]
    },
    {
        "id": "petrov_black",
        "eco": "C42",
        "name": {
            "cs": "Petrova obrana",
            "en": "Petrov's Defence"
        },
        "side": "black",
        "difficulty": 2,
        "idea": {
            "cs": "Symetrická odpověď Nf6 na Nf3.",
            "en": "Symmetrical ...Nf6 against Nf3."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "e7e5",
            "g1f3",
            "g8f6",
            "b1c3",
            "b8c6",
            "d2d3",
            "f8e7"
        ],
        "player_ply_indices": [
            1,
            3,
            5,
            7
        ],
        "checkpoint_ply_indices": [
            3
        ]
    },
    {
        "id": "pirc_classical_black",
        "eco": "B07",
        "name": {
            "cs": "Pirc — klasická",
            "en": "Pirc — Classical"
        },
        "side": "black",
        "difficulty": 2,
        "idea": {
            "cs": "Hypermoderní d6, g6 a fianchetto.",
            "en": "Hypermodern d6, g6, and fianchetto."
        },
        "start_fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "line_uci": [
            "e2e4",
            "d7d6",
            "d2d4",
            "g8f6",
            "b1c3",
            "g7g6",
            "g1f3",
            "f8g7"
        ],
        "player_ply_indices": [
            1,
            3,
            5,
            7
        ],
        "checkpoint_ply_indices": [
            3
        ]
    }
];

    function findOpeningById(id) {
        return OPENING_LINES.filter(function (x) { return x.id === id; })[0] || null;
    }

    function openingStartPayload(line, mode) {
        var body = {
            action: 'start',
            line_id: line.id,
            mode: mode || 'learn',
            side: line.side,
            start_fen: line.start_fen,
            line_uci: line.line_uci,
            player_ply_indices: line.player_ply_indices
        };
        if (line.checkpoint_ply_indices && line.checkpoint_ply_indices.length) {
            body.checkpoint_ply_indices = line.checkpoint_ply_indices;
        }
        return body;
    }

    global.OPENING_LINES = OPENING_LINES;
    global.findOpeningById = findOpeningById;
    global.openingStartPayload = openingStartPayload;
}(typeof window !== 'undefined' ? window : globalThis));
