/**
 * @file uart_commands_table.c
 * @brief UART command name/handler registry (extracted from uart_task.c).
 */

#include "uart_commands_table.h"
#include "uart_task.h"

const uart_command_t uart_commands[] = {
    // System commands
    {"HELP",
     uart_cmd_help,
     "Show command list",
     "",
     false,
     {"?", "H", "", "", ""}},
    {"STATUS",
     uart_cmd_status,
     "System status",
     "",
     false,
     {"S", "INFO", "", "", ""}},
    {"VERSION",
     uart_cmd_version,
     "Version information",
     "",
     false,
     {"VER", "V", "", "", ""}},
    {"MEMORY",
     uart_cmd_memory,
     "Memory information",
     "",
     false,
     {"MEM", "M", "", "", ""}},
    {"HISTORY",
     uart_cmd_history,
     "Command history",
     "",
     false,
     {"HIST", "H", "", "", ""}},

    {"CLEAR",
     uart_cmd_clear,
     "Clear screen",
     "",
     false,
     {"CLS", "C", "", "", ""}},
    {"RESET",
     uart_cmd_reset,
     "System restart",
     "",
     false,
     {"RESTART", "R", "reset", "", ""}},

    // Configuration commands
    {"VERBOSE",
     uart_cmd_verbose,
     "Control logging verbosity",
     "VERBOSE ON/OFF",
     true,
     {"V", "VERB", "", "", ""}},
    {"QUIET",
     uart_cmd_quiet,
     "Toggle quiet mode",
     "",
     false,
     {"Q", "SILENT", "", "", ""}},

    // Game commands
    {"MOVE",
     uart_cmd_move,
     "Make chess move",
     "MOVE <from> <to>",
     true,
     {"M", "MV", "", "", ""}},
    {"UP",
     uart_cmd_up,
     "Lift piece from square",
     "UP <square>",
     true,
     {"U", "LIFT", "", "", ""}},
    {"DN",
     uart_cmd_dn,
     "Drop piece to square",
     "DN <square>",
     true,
     {"D", "DROP", "", "", ""}},
    {"BOARD",
     uart_cmd_board,
     "Show chess board",
     "",
     false,
     {"B", "SHOW", "POS", "", ""}},
    {"LED_BOARD",
     uart_cmd_led_board,
     "Show LED states",
     "",
     false,
     {"LED", "LEDS", "LIGHTS", "", ""}},
    {"GAME_NEW",
     uart_cmd_game_new,
     "Start new game",
     "",
     false,
     {"NEW", "START", "GAME", "", ""}},
    {"GAME_RESET",
     uart_cmd_game_reset,
     "Reset game",
     "",
     false,
     {"GAME_RESET", "GAME_RESTART", "", "", ""}},
    {"GUARD_CLEAR",
     uart_cmd_guard_clear,
     "Force-clear matrix guard (emergency — board must be aligned)",
     "",
     false,
     {"MATRIX_GUARD_CLEAR", "GUARD", "MG_CLEAR", "", ""}},
    {"MOVES",
     uart_cmd_show_moves,
     "Show valid moves",
     "",
     false,
     {"SHOW_MOVES", "VALID", "LEGAL", "", ""}},
    {"UNDO",
     uart_cmd_undo,
     "Undo last move",
     "",
     false,
     {"U", "BACK", "TAKEBACK", "", ""}},
    {"GAME_HISTORY",
     uart_cmd_game_history,
     "Show move history",
     "",
     false,
     {"HIST", "MOVES", "GAME", "", ""}},

    // Starting position check commands
    {"STARTPOS",
     uart_cmd_start_pos_check,
     "Toggle starting position check",
     "STARTPOS ON/OFF",
     true,
     {"POS_CHECK", "POS", "CHECK", "", ""}},

    // Debug commands
    {"SELF_TEST",
     uart_cmd_self_test,
     "Run system self-test",
     "",
     false,
     {"TEST", "", "", "", ""}},
    {"TEST_GAME",
     uart_cmd_test_game,
     "Test game engine",
     "",
     false,
     {"GAME_TEST", "", "", "", ""}},
    {"DEBUG_STATUS",
     uart_cmd_debug_status,
     "Show debug information",
     "",
     false,
     {"DEBUG", "", "", "", ""}},
    {"DEBUG_GAME",
     uart_cmd_debug_game,
     "Show game debug info",
     "",
     false,
     {"GAME_DEBUG", "", "", "", ""}},
    {"DEBUG_BOARD",
     uart_cmd_debug_board,
     "Show board debug info",
     "",
     false,
     {"BOARD_DEBUG", "", "", "", ""}},
    {"BENCHMARK",
     uart_cmd_benchmark,
     "Run performance benchmark",
     "",
     false,
     {"PERF", "", "", "", ""}},
    {"MEMCHECK",
     uart_cmd_memcheck,
     "Check memory usage",
     "",
     false,
     {"MEM_CHECK", "", "", "", ""}},
    {"SHOW_TASKS",
     uart_cmd_show_tasks,
     "Show running tasks",
     "",
     false,
     {"TASKS", "", "", "", ""}},
    {"SHOW_MUTEXES",
     uart_cmd_show_mutexes,
     "Show all mutexes and their status",
     "",
     false,
     {"MUTEXES", "", "", "", ""}},
    {"SHOW_FIFOS",
     uart_cmd_show_fifos,
     "Show all FIFOs and their status",
     "",
     false,
     {"FIFOS", "", "", "", ""}},

    // High Priority Commands
    {"EVAL",
     uart_cmd_eval,
     "Show position evaluation",
     "",
     false,
     {"EVALUATE", "POSITION", "", "", ""}},
    {"GAME_HISTORY",
     uart_cmd_game_history,
     "Show move history",
     "",
     false,
     {"HIST", "MOVES", "GMHIST", "", ""}},
    {"LEDTEST",
     uart_cmd_ledtest,
     "Test all LEDs",
     "",
     false,
     {"LED_TEST", "TEST_LED", "", "", ""}},
    {"PERFORMANCE",
     uart_cmd_performance,
     "Show system performance",
     "",
     false,
     {"PERF", "SYS_PERF", "", "", ""}},
    {"CONFIG",
     uart_cmd_config,
     "Show/set configuration",
     "CONFIG [key] [value]",
     true,
     {"CFG", "SETTINGS", "", "", ""}},

    // Prikazy timeru (zrcadli webove rozhrani)
    {"TIMER",
     uart_cmd_timer,
     "Show timer state (JSON)",
     "",
     false,
     {"TMR", "", "", "", ""}},
    {"TIMER_CONFIG",
     uart_cmd_timer_config,
     "Set time control",
     "TIMER_CONFIG <type|custom> [min inc]",
     true,
     {"TCONF", "TCFG", "", "", ""}},
    {"TIMER_PAUSE",
     uart_cmd_timer_pause,
     "Pause timer",
     "",
     false,
     {"TPAUSE", "", "", "", ""}},
    {"TIMER_RESUME",
     uart_cmd_timer_resume,
     "Resume timer",
     "",
     false,
     {"TRESUME", "", "", "", ""}},
    {"TIMER_RESET",
     uart_cmd_timer_reset,
     "Reset timer",
     "",
     false,
     {"TRESET", "", "", "", ""}},

    // WiFi prikazy
    {"WIFI",
     uart_cmd_wifi,
     "Configure WiFi STA",
     "WIFI <ssid> <password>",
     true,
     {"", "", "", "", ""}},
    {"WIFI_CONNECT",
     uart_cmd_wifi_connect,
     "Connect to WiFi",
     "",
     false,
     {"", "", "", "", ""}},
    {"WIFI_DISCONNECT",
     uart_cmd_wifi_disconnect,
     "Disconnect from WiFi",
     "",
     false,
     {"", "", "", "", ""}},
    {"WIFI_STATUS",
     uart_cmd_wifi_status,
     "Show WiFi status",
     "",
     false,
     {"", "", "", "", ""}},
    {"WIFI_CLEAR",
     uart_cmd_wifi_clear,
     "Clear WiFi config",
     "",
     false,
     {"", "", "", "", ""}},

    // Web control commands
    {"WEB_LOCK",
     uart_cmd_web_lock,
     "Lock/unlock web interface",
     "WEB_LOCK ON/OFF",
     true,
     {"WEBLOCK", "LOCK", "", "", ""}},
    {"WEB_STATUS",
     uart_cmd_web_status,
     "Show web interface status",
     "",
     false,
     {"WEB", "WS", "", "", ""}},
    {"API_TOKEN",
     uart_cmd_api_token,
     "Print or rotate HTTP admin Bearer token (64 hex chars)",
     "API_TOKEN [ROTATE]",
     true,
     {"BOARD_TOKEN", "HTTP_TOKEN", "", "", ""}},
    {"BLE",
     uart_cmd_ble,
     "Bluetooth LE / GATT status (CZECHMATE)",
     "",
     false,
     {"BT", "BLE_STATUS", "", "", ""}},

    // MQTT commands
    {"MQTT_CONFIG",
     uart_cmd_mqtt_config,
     "Configure MQTT broker",
     "MQTT_CONFIG <host> [port] [username] [password]",
     true,
     {"MQTT", "MQTT_CFG", "", "", ""}},
    {"MQTT_STATUS",
     uart_cmd_mqtt_status,
     "Show MQTT status",
     "",
     false,
     {"MQTT_ST", "MQTT_S", "", "", ""}},
    {"MQTT_TEST",
     uart_cmd_mqtt_test,
     "Test MQTT connection",
     "",
     false,
     {"MQTT_T", "", "", "", ""}},

    // Demo mode commands
    {"DEMO",
     uart_cmd_demo,
     "Toggle demo/screensaver mode",
     "DEMO ON/OFF",
     true,
     {"SCREENSAVER", "AUTO", "", "", ""}},
    {"DEMO_STATUS",
     uart_cmd_demo_status,
     "Show demo mode status",
     "",
     false,
     {"", "", "", "", ""}},

    // Medium Priority Commands
    {"CASTLE",
     uart_cmd_castle,
     "Castle (kingside/queenside)",
     "CASTLE <kingside|queenside>",
     true,
     {"CASTLING", "O-O", "", "", ""}},
    {"PROMOTE",
     uart_cmd_promote,
     "Promote pawn",
     "PROMOTE <square>=<piece>",
     true,
     {"PROMOTION", "PROMO", "", "", ""}},
    {"MATRIXTEST",
     uart_cmd_matrixtest,
     "Test matrix scanning",
     "",
     false,
     {"MATRIX_TEST", "TEST_MATRIX", "", "", ""}},

    // Component Control Commands
    {"COMPONENT_OFF",
     uart_cmd_component_off,
     "Turn off component",
     "COMPONENT_OFF <matrix|led|wifi>",
     true,
     {"OFF", "DISABLE", "", "", ""}},
    {"COMPONENT_ON",
     uart_cmd_component_on,
     "Turn on component",
     "COMPONENT_ON <matrix|led|wifi>",
     true,
     {"ON", "ENABLE", "", "", ""}},

    // Endgame Commands
    {"ENDGAME_WHITE",
     uart_cmd_endgame_white,
     "Endgame - White wins",
     "",
     false,
     {"WHITE_WINS", "WHITE_VICTORY", "", "", ""}},
    {"ENDGAME_BLACK",
     uart_cmd_endgame_black,
     "Endgame - Black wins",
     "",
     false,
     {"BLACK_WINS", "BLACK_VICTORY", "", "", ""}},

    // Animation Test Commands
    {"TEST_MOVE_ANIM",
     uart_cmd_test_move_anim,
     "Test move animation",
     "TEST_MOVE_ANIM",
     false,
     {"MOVE_TEST", "TEST_MOVE", "", "", ""}},
    {"TEST_PLAYER_ANIM",
     uart_cmd_test_player_anim,
     "Test player change animation",
     "TEST_PLAYER_ANIM",
     false,
     {"PLAYER_TEST", "TEST_PLAYER", "", "", ""}},
    {"TEST_CASTLE_ANIM",
     uart_cmd_test_castle_anim,
     "Test castling animation",
     "TEST_CASTLE_ANIM",
     false,
     {"CASTLE_TEST", "TEST_CASTLE", "", "", ""}},
    {"TEST_PROMOTE_ANIM",
     uart_cmd_test_promote_anim,
     "Test promotion animation",
     "TEST_PROMOTE_ANIM",
     false,
     {"PROMOTE_TEST", "TEST_PROMOTE", "", "", ""}},
    {"TEST_ENDGAME_ANIM",
     uart_cmd_test_endgame_anim,
     "Test endgame animation",
     "TEST_ENDGAME_ANIM",
     false,
     {"ENDGAME_TEST", "TEST_ENDGAME", "", "", ""}},

    // Endgame Animation Style Commands
    {"ENDGAME_WAVE",
     uart_cmd_endgame_wave,
     "Endgame wave animation",
     "ENDGAME_WAVE",
     false,
     {"WAVE", "ENDGAME_0", "", "", ""}},
    {"ENDGAME_CIRCLES",
     uart_cmd_endgame_circles,
     "Endgame circles animation",
     "ENDGAME_CIRCLES",
     false,
     {"CIRCLES", "ENDGAME_1", "", "", ""}},
    {"ENDGAME_CASCADE",
     uart_cmd_endgame_cascade,
     "Endgame cascade animation",
     "ENDGAME_CASCADE",
     false,
     {"CASCADE", "ENDGAME_2", "", "", ""}},
    {"ENDGAME_FIREWORKS",
     uart_cmd_endgame_fireworks,
     "Endgame fireworks animation",
     "ENDGAME_FIREWORKS",
     false,
     {"FIREWORKS", "ENDGAME_3", "", "", ""}},
    {"DRAW_SPIRAL",
     uart_cmd_endgame_draw_spiral,
     "Draw spiral animation",
     "DRAW_SPIRAL",
     false,
     {"SPIRAL", "DRAW_0", "", "", ""}},
    {"DRAW_PULSE",
     uart_cmd_endgame_draw_pulse,
     "Draw pulse animation",
     "DRAW_PULSE",
     false,
     {"PULSE", "DRAW_1", "", "", ""}},

    // Endgame animation control
    {"STOP_ENDGAME",
     uart_cmd_stop_endgame,
     "Stop endless endgame animation",
     "STOP_ENDGAME",
     false,
     {"STOP", "END_STOP", "", "", ""}},

    {"CLI",
     uart_cmd_cli,
     "Unified console panel (flash/partitions/web/OTA/BLE/snapshot)",
     "CLI HELP",
     false,
     {"CONTROL", "PANEL", "", "", ""}},

    // System Commands

    // End marker
    {NULL, NULL, "", "", false, {"", "", "", "", ""}}};
