#!/usr/bin/env python3
"""One-off helper to build app_en.arb / app_cs.arb from parallel string tables."""
import json
from pathlib import Path

# (key, en, cs) — add rows as UI grows
ROWS: list[tuple[str, str, str]] = [
  # App / nav
  ("appTitle", "CzechMate", "CzechMate"),
  ("navPlay", "Play", "Hra"),
  ("navAnalysis", "Analysis", "Analýza"),
  ("navPuzzle", "Puzzle", "Puzzle"),
  ("navProgress", "Progress", "Pokrok"),
  ("navSettings", "Settings", "Nastavení"),
  # Language
  ("settingsLanguage", "Language", "Jazyk"),
  ("languageSystem", "System", "Systém"),
  ("languageEnglish", "English", "Angličtina"),
  ("languageCzech", "Czech", "Čeština"),
  ("languageDescription", "Choose app language. System follows the device; unsupported languages default to English.", "Zvol jazyk aplikace. Systém následuje telefon; ostatní jazyky se zobrazí v angličtině."),
  # Onboarding
  ("onboardingWelcomeTitle", "Welcome to CZECHMATE", "Vítej v CZECHMATE"),
  ("onboardingSkip", "Skip", "Přeskočit"),
  ("onboardingNext", "Next", "Další"),
  ("onboardingStart", "Start playing", "Začít hrát"),
  ("onboard1Title", "Smart chessboard", "Chytrá šachovnice"),
  ("onboard1Body", "Connect your CZECHMATE board over Wi‑Fi or Bluetooth and play with live sync.", "Připoj šachovnici CZECHMATE přes Wi‑Fi nebo Bluetooth a hraj s živou synchronizací."),
  ("onboard2Title", "Set up the pieces", "Rozestav figury"),
  ("onboard2Body", "Before powering on, place pieces in the starting position. The app will align with the board automatically.", "Před zapnutím postav figury do výchozí pozice. Aplikace se s deskou sama srovná."),
  ("onboard3Title", "LED hints", "LED nápovědy"),
  ("onboard3Body", "The board can highlight moves with LEDs. Hint depth is configured under Settings → Board NVS.", "Deska umí zvýraznit tahy LEDkami. Hloubku nápovědy nastavíš v Nastavení → NVS desky."),
  ("onboard4Title", "Start a game", "Začni partii"),
  ("onboard4Body", "On Play, tap New game and pick a time control. Flip the board (White or Black on bottom) from Game controls or Settings.", "Na kartě Hra klepni Nová hra a zvol časovou kontrolu. Otočení strany (bílá nebo černá dole) najdeš v ovládání hry nebo v nastavení."),
  ("onboard5Title", "Coach & analysis", "Trenér a analýza"),
  ("onboard5Body", "Turn on learning mode and Stockfish evaluation on Analysis for deeper insight.", "Zapni výukový režim a Stockfish eval na Analýze pro hlubší poznatky."),
  # Network
  ("netNoInternetTitle", "No internet", "Bez internetu"),
  ("netNoInternetBody", "Stockfish (chess-api), Lichess, and other cloud features need internet. You can still use the board over Bluetooth offline.", "Stockfish (chess-api), Lichess a další cloudové funkce vyžadují internet. Po Bluetooth ale desku používáš i offline."),
  ("netNotOnWifiTitle", "Not on Wi‑Fi", "Nejsi na Wi‑Fi"),
  ("netNotOnWifiBody", "chess-api usually works over mobile data. To open the board’s HTTP API on a LAN IP, the phone typically needs Wi‑Fi on the same network. If you are only on the board’s hotspot without internet, DNS for chess-api / Lichess may fail — temporarily disable that Wi‑Fi, enable mobile data, or use dual‑stack (Wi‑Fi + cellular data) if your OS allows. The app cannot force traffic to cellular while Wi‑Fi is the default route.", "chess-api většinou funguje přes mobilní data. K HTTP API desky na LAN IP telefon typicky potřebuje Wi‑Fi ve stejné síti. Pokud jsi jen na hotspotu desky bez internetu, DNS pro chess-api / Lichess může selhat — zkus Wi‑Fi na chvíli vypnout, zapnout mobilní data nebo dual‑stack, pokud systém dovolí. Aplikace nemůže donutit provoz na LTE, když výchozí trasa je Wi‑Fi."),
  # Session / connection errors
  ("errInvalidBoardUrl", "Invalid board URL — hostname missing. Use http://192.168.4.1 or your board STA IP.", "Neplatná adresa desky — chybí hostitel. Použij http://192.168.4.1 nebo STA IP desky."),
  ("errNoSavedBle", "No saved Bluetooth board. Open Board discovery and pair your CZECHMATE board.", "Žádná uložená Bluetooth deska. Otevři Objevování desky a spáruj CZECHMATE."),
  ("errDemoNoSnapshot", "Demo board has no snapshot.", "Demo deska nemá snapshot."),
  ("errConnectBeforeMoves", "Connect to the board over Wi‑Fi or Bluetooth before sending moves from the app.", "Než odešleš tah z aplikace, připoj desku přes Wi‑Fi nebo Bluetooth."),
  ("errSetupNeedsConnection", "Setup wizard requires an active board connection (Wi‑Fi or Bluetooth).", "Průvodce nastavením vyžaduje aktivní připojení k desce (Wi‑Fi nebo Bluetooth)."),
  ("errOtaHttps", "OTA requires an HTTPS URL to the .bin file.", "OTA vyžaduje HTTPS URL souboru .bin."),
  ("errOtaMock", "OTA is not available with the mock board.", "OTA není dostupná u demo desky."),
  ("errOtaConnectFirst", "Connect the board over Wi‑Fi or Bluetooth, then try the update again.", "Připoj desku přes Wi‑Fi nebo Bluetooth a pak zkus aktualizaci znovu."),
  ("errHintsNeedConnection", "Hint LEDs require a board connection. Pair via Bluetooth or connect Wi‑Fi first.", "Nápovědní LED vyžadují připojení desky. Nejprve Bluetooth nebo Wi‑Fi."),
  ("errNoActiveSession", "No active board session. Connect via Wi‑Fi or Bluetooth from Board discovery.", "Žádná aktivní session desky. Připoj ji přes Wi‑Fi nebo Bluetooth z Objevování desky."),
  ("errBrightnessNeedsBoard", "Brightness control needs a connected board (Wi‑Fi or Bluetooth).", "Jas vyžaduje připojenou desku (Wi‑Fi nebo Bluetooth)."),
  ("errLampNeedsBoard", "Lamp control needs a connected board (Wi‑Fi or Bluetooth).", "Ovládání lampy vyžaduje připojenou desku (Wi‑Fi nebo Bluetooth)."),
  ("errGameLampNeedsBoard", "Game lamp mode requires a connected board (Wi‑Fi or Bluetooth).", "Režim herní lampy vyžaduje připojenou desku (Wi‑Fi nebo Bluetooth)."),
  ("errAutoLampNeedsBoard", "Auto lamp timeout requires a connected board (Wi‑Fi or Bluetooth).", "Automatický čas lampy vyžaduje připojenou desku (Wi‑Fi nebo Bluetooth)."),
  # Move evaluation
  ("moveEvalExcellentBest", "Excellent move — that was the best move.", "Skvělý tah — byl to nejlepší možný tah."),
  ("moveEvalExcellentEngine", "Excellent — matches the engine best move.", "Výborně — přesně jako engine."),
  ("moveEvalWeakerNoScore", "Weaker move (no exact score). Stronger was {best}.", "Slabší tah (bez přesného skóre). Lepší byl {best}."),
  ("moveEvalGoodLoss", "Good move — small loss (~{cp} cp).", "Dobrý tah — malá ztráta (~{cp} cp)."),
  ("moveEvalInaccuracy", "Inaccuracy — about {cp} cp worse. Stronger was {best}.", "Nepřesnost — cca o {cp} cp horší. Silnější byl {best}."),
  ("moveEvalMistake", "Mistake — about {cp} cp worse. Better was {best}.", "Chyba — cca o {cp} cp horší. Lepší byl {best}."),
  ("moveEvalBlunder", "Blunder — about {cp} cp worse. Much better was {best}.", "Hrubka — cca o {cp} cp horší. Mnohem lepší byl {best}."),
  ("moveEvalFailed", "Evaluation failed: {error}", "Evaluace selhala: {error}"),
  # Game end / export / report
  ("pgnEventHeader", "CZECHMATE", "CZECHMATE"),
  ("pgnOpeningPrefix", "Start", "Začátek"),
  ("sharePgnSubject", "Chess game (PGN)", "Šachová partie (PGN)"),
  ("shareSummaryNotReady", "Summary isn’t ready yet — try again in a moment.", "Shrnutí ještě není připravené — zkus to za chvíli."),
  ("shareExportFailed", "Export failed: {error}", "Export selhal: {error}"),
  ("sharePngEncodeError", "Could not encode image as PNG.", "Obrázek se nepodařilo zakódovat jako PNG."),
  ("shareGameSummaryMeta", "{result} · {duration} · {moves} moves", "{result} · {duration} · {moves} tahů"),
  ("shareGameSummaryLine", "Game summary — CzechMate · {meta}", "Shrnutí partie — CzechMate · {meta}"),
  ("reportNoGameData", "No game data.", "Žádná data partie."),
  ("reportMoveEvaluation", "Move evaluation", "Hodnocení tahů"),
  ("reportNoStockfishData", "No Stockfish data — enable move evaluation and play a game.", "Žádná Stockfish data — zapni hodnocení tahů a odehraj partii."),
  ("reportEvalPerspective", "From White’s perspective (+ favors White)", "Z pohledu bílého (+ pro bílého)"),
  ("reportMoveTiming", "Move timing", "Časování tahů"),
  ("reportTimingUnavailable", "Move timestamps weren’t included — timing charts are unavailable.", "Chybí časové značky tahů — grafy času nejsou k dispozici."),
  ("reportElapsedTime", "Elapsed time", "Uplynulý čas"),
  ("reportElapsedCaption", "Running total from game start by half-move", "Součet od začátku partie po půltazích"),
  ("reportHalfMoveAxis", "half-move → minutes", "půltah → minuty"),
  ("reportTimePerMove", "Time per move", "Čas na tah"),
  ("reportSecondsSincePrev", "Seconds since previous move", "Sekundy od předchozího tahu"),
  ("colorWhite", "White", "Bílý"),
  ("colorBlack", "Black", "Černý"),
  ("reportMaterialCaptured", "Material captured · White {w} pts · Black {b} pts", "Braný materiál · Bílý {w} b. · Černý {b} b."),
  ("reportAppBarTitle", "Game summary", "Shrnutí partie"),
  ("reportDone", "Done", "Hotovo"),
  ("reportResultHeading", "Result", "Výsledek"),
  ("reportShareHeading", "Share", "Sdílení"),
  ("reportShareExportHint", "Export the summary card above as a PNG, then use the system share sheet.", "Exportuj kartu výše jako PNG a pak použij systémové sdílení."),
  ("reportSharePreparing", "Preparing…", "Připravuji…"),
  ("reportShareSummaryImage", "Share summary image", "Sdílet obrázek shrnutí"),
  ("reportSharePgn", "Share PGN file", "Sdílet soubor PGN"),
  ("reportClock", "Clock", "Hodiny"),
  ("reportMinutesShort", "{n} min", "{n} min"),
  ("reportFinalFen", "Final FEN", "Výsledné FEN"),
  ("resultWhiteWins", "White wins", "Výhra bílého"),
  ("resultBlackWins", "Black wins", "Výhra černého"),
  ("resultDraw", "Draw", "Remíza"),
  ("resultGameEnded", "Game ended", "Partie skončila"),
  ("endReasonUnknown", "Unknown result", "Neznámý výsledek"),
  ("endReasonGameOver", "Game over", "Konec partie"),
  ("endReasonCheckmate", "Checkmate", "Mat"),
  ("endReasonStalemate", "Stalemate", "Pat"),
  ("endReasonFinished", "Finished", "Dohráno"),
  ("statTime", "TIME", "ČAS"),
  ("statMoves", "MOVES", "TAHY"),
  ("statWhiteAvg", "WHITE Ø", "BÍLÝ Ø"),
  ("statBlackAvg", "BLACK Ø", "ČERNÝ Ø"),
  ("durationDash", "—", "—"),
  ("secondsShort", "{n}s", "{n}s"),
  ("minutesSeconds", "{m}:{s}", "{m}:{s}"),
  ("hoursMinutesSeconds", "{h}h {mm}m {s}s", "{h}h {mm}m {s}s"),
  # Common UI
  ("commonClose", "Close", "Zavřít"),
  ("commonCancel", "Cancel", "Zrušit"),
  ("commonOk", "OK", "OK"),
  ("commonSave", "Save", "Uložit"),
  ("commonContinue", "Continue", "Pokračovat"),
  ("commonRetry", "Retry", "Opakovat"),
  ("commonLoading", "Loading…", "Načítání…"),
  ("commonError", "Error", "Chyba"),
  ("commonYes", "Yes", "Ano"),
  ("commonNo", "No", "Ne"),
  ("lastErrorTitle", "Last error", "Poslední chyba"),
  ("telemetryPrivacyTitle", "Privacy", "Soukromí"),
  ("telemetryPrivacyBody", "This build does not send analytics. Traffic goes only to your board on the local network or over Bluetooth.", "Tento build neodesílá analytiku. Provoz jde jen na tvou desku v lokální síti nebo přes Bluetooth."),
  ("telemetryIcloudTitle", "iCloud", "iCloud"),
  ("telemetryIcloudBody", "Game data stays on device unless you export or enable sync elsewhere.", "Data partie zůstávají na zařízení, dokud je neexportuješ nebo nezapneš synchronizaci jinde."),
  # Board discovery
  ("discoveryTitle", "Find board", "Najít desku"),
  ("discoveryBlePermissionAndroid", "Allow Bluetooth permissions in system settings to scan for BLE boards.", "Povol Bluetooth oprávnění v nastavení systému, aby šlo desku vyhledat."),
  ("discoveryBleScanFailed", "Bluetooth scan failed: {error}", "Sken Bluetooth selhal: {error}"),
  ("discoveryIntro", "Tap a board in the list. The app connects over Bluetooth and may switch to Wi‑Fi (STA) when the board is online on the network and your phone has Wi‑Fi.", "Klepni na desku v seznamu. Aplikace se přes Bluetooth spojí a podle nastavení může přejít na Wi‑Fi (STA), pokud je deska online v síti a telefon má Wi‑Fi."),
  ("transportDisconnected", "Disconnected", "Odpojeno"),
  ("transportDemo", "Demo mode", "Demo režim"),
  ("transportWifi", "Wi‑Fi", "Wi‑Fi"),
  ("transportBluetooth", "Bluetooth", "Bluetooth"),
  ("transportConnecting", "{transport} · connecting…", "{transport} · připojuji…"),
  ("defaultBoardName", "CZECHMATE board", "CZECHMATE deska"),
  ("discoveryWifiUrlHint", "Board URL (http://…)", "Adresa desky (http://…)"),
  ("discoveryConnectWifi", "Connect via Wi‑Fi", "Připojit přes Wi‑Fi"),
  ("discoveryFindBle", "Find board (Bluetooth)", "Najít desku (Bluetooth)"),
  ("discoveryScanning", "Scanning…", "Skenuji…"),
  ("discoveryStopScan", "Stop scan", "Zastavit sken"),
  ("discoveryManualUrl", "Manual URL entry", "Ruční zadání URL"),
  ("connectionModeAuto", "Auto (Bluetooth then Wi‑Fi)", "Auto (Bluetooth pak Wi‑Fi)"),
  ("connectionModeWifiOnly", "Wi‑Fi only", "Jen Wi‑Fi"),
  ("connectionModeBleOnly", "Bluetooth only", "Jen Bluetooth"),
  ("preferBleOnlyTitle", "Bluetooth only (don’t switch to Wi‑Fi)", "Jen Bluetooth (nepřepínat na Wi‑Fi)"),
  ("preferBleOnlySubtitle", "After BLE connect, stay on Bluetooth even if the board knows a Wi‑Fi URL.", "Po připojení přes BLE zůstat na Bluetooth, i když deska zná Wi‑Fi adresu."),
  ("mockBoardTileTitle", "Demo board (no hardware)", "Demo deska (bez hardwaru)"),
  ("mockBoardTileSubtitle", "Uses bundled snapshot for UI testing.", "Používá zabalený snapshot pro test UI."),
  ("sessionConnectedWifi", "Connected via Wi‑Fi", "Připojeno přes Wi‑Fi"),
  ("sessionConnectedBle", "Connected via Bluetooth", "Připojeno přes Bluetooth"),
  ("sessionConnectedMock", "Demo board active", "Aktivní demo deska"),
  ("allowBluetoothSettings", "Allow Bluetooth permissions in settings to scan for BLE boards.", "Pro sken BLE desek povol Bluetooth v nastavení systému."),
  # Game screen
  ("gameAppBarTitle", "czechmate", "czechmate"),
  ("gameConnectionTooltip", "Board connection", "Připojení k šachovnici"),
  ("gameNewGame", "New game", "Nová hra"),
  ("gameHintThinking", "Thinking…", "Přemýšlím…"),
  ("gameHint", "Hint", "Nápověda"),
  ("gamePauseClock", "Pause clock", "Pozastavit hodiny"),
  ("gameResumeClock", "Resume clock", "Pokračovat v hodinách"),
  ("gameClearHintLeds", "Clear hint LEDs", "Zrušit nápovědní LED"),
  ("gameNoSnapshotYet", "No board snapshot yet.", "Zatím žádný snapshot desky."),
  ("gameFindBoard", "Find board", "Najít desku"),
  ("gameFindBoardSubtitle", "Connect Wi‑Fi or Bluetooth to load the live position.", "Připoj Wi‑Fi nebo Bluetooth pro živou pozici."),
  ("gameControlsTitle", "Game controls", "Ovládání hry"),
  ("gameHistory", "History", "Historie"),
  ("gameReturnLive", "Return to live game", "Zpět na živou hru"),
  ("gameExitPuzzleCheck", "Exit puzzle check (keep position)", "Ukončit kontrolu puzzlu (pozice zůstane)"),
  ("gameFindBoardTooltip", "Find board", "Najít desku"),
  ("gameLayoutTooltip", "Layout mode", "Režim rozvržení"),
  ("gameLayoutStandard", "Standard", "Standardní"),
  ("gameLayoutBoardOnly", "Board only", "Jen deska"),
  ("gameCoachRailShow", "Show AI coach column", "Zobrazit sloupec AI trenéra"),
  ("gameCoachRailHide", "Hide AI coach column", "Skrýt sloupec AI trenéra"),
  ("gameControlsTooltip", "Game controls", "Ovládání hry"),
  ("gameAnalysisTooltip", "Analysis", "Analýza"),
  ("gameSummaryTooltip", "Game summary", "Shrnutí partie"),
  ("gameDisconnectTooltip", "Disconnect session", "Odpojit session"),
  ("gameHidePanelTooltip", "Hide panel", "Skrýt panel"),
  ("gamePuzzleMovesProgress", "Moves {played} / {total}", "Tahy {played} / {total}"),
  ("gameHintTransient", "Hint: {from}→{to}{evalSuffix}", "Nápověda: {from}→{to}{evalSuffix}"),
  ("gameBestMoveSnack", "Best move: {from}→{to}", "Nejlepší tah: {from}→{to}"),
  ("gameHintFailed", "Hint failed: {error}", "Nápověda selhala: {error}"),
  ("gameDemoBoardSnack", "Demo board: {feature} only works over Bluetooth or Wi‑Fi to real hardware.", "Demo deska: {feature} funguje jen přes Bluetooth nebo Wi‑Fi na reálný hardware."),
  ("gameDesktopPlayTitle", "Play — desktop", "Hra — desktop"),
  ("gameDesktopPlaySubtitle", "Tap the indicator top-left to manage connection (Wi‑Fi, Bluetooth, mock) — same as iOS.", "Klepnutím na indikátor vlevo nahoře otevřeš správu připojení (Wi‑Fi, Bluetooth, mock) — stejně jako na iOS."),
  ("stockfishEvalFailedSnack", "Evaluation failed: {msg}", "Evaluace selhala: {msg}"),
  # Firmware daily prompt dialog
  ("firmwareDialogTitle", "Board firmware update", "Aktualizace firmware desky"),
  ("firmwareDialogVersions", "Server has {serverVer}, your board reports {boardVer}.", "Na serveru je {serverVer}, deska hlásí {boardVer}."),
  ("firmwareDialogHttpsNote", "The board downloads over HTTPS (Wi‑Fi STA). The phone only sends the link.", "Deska stahuje přes HTTPS (Wi‑Fi STA). Telefon posílá jen odkaz."),
  ("firmwareTurnOffReminders", "Turn off reminders", "Vypnout připomínky"),
  ("firmwareNotNow", "Not now", "Teď ne"),
  ("firmwareUpdateAction", "Update", "Aktualizovat"),
]

PLACEHOLDER_META = {
  "moveEvalWeakerNoScore": {"placeholders": {"best": {"type": "String"}}},
  "moveEvalGoodLoss": {"placeholders": {"cp": {"type": "int"}}},
  "moveEvalInaccuracy": {"placeholders": {"cp": {"type": "int"}, "best": {"type": "String"}}},
  "moveEvalMistake": {"placeholders": {"cp": {"type": "int"}, "best": {"type": "String"}}},
  "moveEvalBlunder": {"placeholders": {"cp": {"type": "int"}, "best": {"type": "String"}}},
  "moveEvalFailed": {"placeholders": {"error": {"type": "String"}}},
  "shareExportFailed": {"placeholders": {"error": {"type": "String"}}},
  "reportMaterialCaptured": {"placeholders": {"w": {"type": "int"}, "b": {"type": "int"}}},
  "shareGameSummaryMeta": {"placeholders": {"result": {"type": "String"}, "duration": {"type": "String"}, "moves": {"type": "int"}}},
  "shareGameSummaryLine": {"placeholders": {"meta": {"type": "String"}}},
  "reportMinutesShort": {"placeholders": {"n": {"type": "String"}}},
  "secondsShort": {"placeholders": {"n": {"type": "int"}}},
  "minutesSeconds": {"placeholders": {"m": {"type": "int"}, "s": {"type": "String"}}},
  "hoursMinutesSeconds": {"placeholders": {"h": {"type": "int"}, "mm": {"type": "int"}, "s": {"type": "int"}}},
  "discoveryBleScanFailed": {"placeholders": {"error": {"type": "String"}}},
  "transportConnecting": {"placeholders": {"transport": {"type": "String"}}},
  "gamePuzzleMovesProgress": {"placeholders": {"played": {"type": "int"}, "total": {"type": "int"}}},
  "gameHintTransient": {"placeholders": {"from": {"type": "String"}, "to": {"type": "String"}, "evalSuffix": {"type": "String"}}},
  "gameBestMoveSnack": {"placeholders": {"from": {"type": "String"}, "to": {"type": "String"}}},
  "gameHintFailed": {"placeholders": {"error": {"type": "String"}}},
  "gameDemoBoardSnack": {"placeholders": {"feature": {"type": "String"}}},
  "stockfishEvalFailedSnack": {"placeholders": {"msg": {"type": "String"}}},
  "firmwareDialogVersions": {"placeholders": {"serverVer": {"type": "String"}, "boardVer": {"type": "String"}}},
}


def build_arb(locale: str, lang_row_index: int) -> dict:
  out: dict = {"@@locale": locale}
  for row in ROWS:
    key, en, cs = row
    out[key] = en if lang_row_index == 0 else cs
    meta_key = f"@{key}"
    if key in PLACEHOLDER_META:
      out[meta_key] = PLACEHOLDER_META[key]
  return out


def main() -> None:
  root = Path(__file__).resolve().parents[1]
  l10n = root / "lib" / "l10n"
  l10n.mkdir(parents=True, exist_ok=True)
  (l10n / "app_en.arb").write_text(
    json.dumps(build_arb("en", 0), ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
  )
  (l10n / "app_cs.arb").write_text(
    json.dumps(build_arb("cs", 1), ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
  )
  print(f"Wrote {l10n / 'app_en.arb'} ({len(ROWS)} keys)")


if __name__ == "__main__":
  main()
