#!/usr/bin/env python3
"""Concatenate web/js modules into web/chess_app.js (no bundler).

Source of truth: web/js/*.js modules + app_main.js
Output: web/chess_app.js (for embed_chess_js.py / syntax check)

Usage:
    python3 components/web_server_task/tools/concat_web_js.py
"""

from __future__ import annotations

import sys
from pathlib import Path

COMPONENT_DIR = Path(__file__).resolve().parent.parent
WEB_DIR = COMPONENT_DIR / "web"
OUTPUT = WEB_DIR / "chess_app.js"

MODULES = [
    WEB_DIR / "js" / "matrix_guard.js",
    WEB_DIR / "js" / "api.js",
    WEB_DIR / "js" / "prefs.js",
    WEB_DIR / "js" / "app_main.js",
]

BANNER = """// ============================================================================
// CHESS WEB APP — generated by tools/concat_web_js.py (do not edit by hand)
// Edit web/js/*.js modules, then: python3 components/web_server_task/tools/concat_web_js.py
// ============================================================================

"""


def main() -> int:
    missing = [p for p in MODULES if not p.is_file()]
    if missing:
        for p in missing:
            print(f"Missing module: {p}", file=sys.stderr)
        return 1

    parts = [BANNER]
    for path in MODULES:
        parts.append(path.read_text(encoding="utf-8"))
        if not parts[-1].endswith("\n"):
            parts[-1] += "\n"
        parts.append("\n")

    OUTPUT.write_text("".join(parts), encoding="utf-8")
    line_count = OUTPUT.read_text(encoding="utf-8").count("\n")
    byte_count = OUTPUT.stat().st_size
    print(f"Wrote {OUTPUT} ({byte_count} bytes, {line_count} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
